"""
Parameter recovery tests using likelihood slicing.

Tests validate that:
1. Forward models are implemented correctly
2. Likelihood functions are well-behaved
3. True parameters can be recovered in principle

Each test generates synthetic data with known parameters, then slices the
log-likelihood along each parameter dimension to verify it peaks near the
true value.

Diagnostic plots are generated by default showing:
- 2x3 panel plots: [noisy|true|noisy-true] and [noisy|model|noisy-model]
- Likelihood slices for each parameter with true value and recovered peak
"""

import pytest
import jax.numpy as jnp
import numpy as np
from typing import Dict, Tuple

from kl_pipe.parameters import ImagePars
from kl_pipe.velocity import CenteredVelocityModel, OffsetVelocityModel
from kl_pipe.intensity import (
    InclinedExponentialModel,
    InclinedSpergelModel,
    BulgeDiskModel,
)
from kl_pipe.source import SourceModel
from kl_pipe.lines import EmissionLine, LINE_LAMBDAS
from kl_pipe.synthetic import SyntheticVelocity, SyntheticIntensity
from kl_pipe.priors import PriorDict, Uniform
from kl_pipe.sampling.task import InferenceTask
from kl_pipe.utils import build_map_grid_from_image_pars, get_test_dir
from kl_pipe.observation import build_image_obs, build_velocity_obs, build_grism_obs
from kl_pipe.dispersion import build_grism_pars_for_line

# Import our shared test utilities
from test_utils import (
    TestConfig,
    slice_all_parameters,
    plot_likelihood_slices,
    assert_parameter_recovery,
    assert_noiseless_recovery,
    assert_slice_curvature_references,
    assert_noiseless_gates,
    make_aperture_mask,
)
from kl_pipe.diagnostics.imaging import plot_data_comparison_panels


# ==============================================================================
# Pytest Fixtures
# ==============================================================================


@pytest.fixture(scope="module")
def test_config():
    """
    Test configuration fixture.

    This replaces global variables and makes configuration explicit.
    To modify behavior, edit TestConfig in test_utils.py.
    """

    out_dir = get_test_dir() / "out" / "likelihood_slices"
    config = TestConfig(out_dir, include_poisson_noise=False)
    config.output_dir.mkdir(parents=True, exist_ok=True)

    return config


@pytest.fixture
def velocity_grids(test_config):
    """Pre-computed coordinate grids for velocity tests (32x32)."""
    X, Y = build_map_grid_from_image_pars(
        test_config.image_pars_velocity, unit='arcsec', centered=True
    )
    return X, Y


@pytest.fixture
def intensity_grids(test_config):
    """Pre-computed coordinate grids for intensity tests (64x64)."""
    X, Y = build_map_grid_from_image_pars(
        test_config.image_pars_intensity, unit='arcsec', centered=True
    )
    return X, Y


# ==============================================================================
# Noiseless gate tables (accuracy budgets + error-bar references)
# ==============================================================================
#
# Every recovery test in this module runs on noise-free data and asserts two
# deterministic gates per sampled parameter (see assert_noiseless_gates in
# test_utils): recovery within an absolute accuracy budget, and a slice
# error bar within 20% of its frozen reference. Budgets: 10x the error
# measured on each frozen scene, floored at 1e-5 of the scan half-range,
# rounded up to one significant figure. References are quoted at each
# test's nominal SNR (the snr default in its signature), which sets the
# variance normalization only -- the data carries no noise. Frozen
# 2026-07-08 (commit b90779a), generated by this module's own measure
# mode:
#   KLPIPE_TEST_MEASURE=1 pytest tests/test_likelihood_slices.py -s
# Re-freeze only deliberately, with the reason recorded here.
_GATES = {
    'centered_velocity_base': {
        'budgets': {
            'cosi': 3e-03,
            'g1': 2e-05,
            'g2': 3e-03,
            'theta_int': 3e-04,
            'vel.rscale': 2e-02,
            'vel.v0': 3e-05,
            'vel.vcirc': 4e-01,
        },
        'sigma_refs': {
            'cosi': 0.00133,
            'g1': 0.00139,
            'g2': 0.00115,
            'theta_int': 0.00105,
            'vel.rscale': 0.00821,
            'vel.v0': 0.0479,
            'vel.vcirc': 0.205,
        },
    },
    'centered_velocity_with_shear': {
        'budgets': {
            'cosi': 3e-03,
            'g1': 3e-04,
            'g2': 3e-03,
            'theta_int': 5e-05,
            'vel.rscale': 2e-02,
            'vel.v0': 3e-05,
            'vel.vcirc': 4e-01,
        },
        'sigma_refs': {
            'cosi': 0.0013,
            'g1': 0.0014,
            'g2': 0.00116,
            'theta_int': 0.0011,
            'vel.rscale': 0.0082,
            'vel.v0': 0.049,
            'vel.vcirc': 0.204,
        },
    },
    'offset_velocity': {
        'budgets': {
            'cosi': 3e-03,
            'g1': 6e-05,
            'g2': 2e-03,
            'theta_int': 1e-04,
            'vel.rscale': 2e-02,
            'vel.v0': 4e-03,
            'vel.vcirc': 4e-01,
            'vel.x0': 1e-03,
            'vel.y0': 2e-04,
        },
        'sigma_refs': {
            'cosi': 0.00139,
            'g1': 0.00126,
            'g2': 0.00107,
            'theta_int': 0.000947,
            'vel.rscale': 0.00829,
            'vel.v0': 0.0462,
            'vel.vcirc': 0.202,
            'vel.x0': 0.00483,
            'vel.y0': 0.00432,
        },
    },
    'inclined_exponential': {
        'budgets': {
            'F087.flux': 3e-06,
            'F087.rscale': 2e-04,
            'F087.x0': 1e-06,
            'F087.y0': 1e-06,
            'cosi': 4e-05,
            'g1': 3e-07,
            'g2': 3e-07,
            'theta_int': 2e-06,
        },
        'sigma_refs': {
            'F087.flux': 0.001,
            'F087.rscale': 0.00246,
            'F087.x0': 0.00352,
            'F087.y0': 0.00352,
            'cosi': 0.000955,
            'g1': 0.00111,
            'g2': 0.00117,
            'theta_int': 0.00328,
        },
    },
    'inclined_exponential_with_shear': {
        'budgets': {
            'F087.flux': 3e-06,
            'F087.rscale': 2e-04,
            'F087.x0': 1e-06,
            'F087.y0': 1e-06,
            'cosi': 4e-05,
            'g1': 8e-08,
            'g2': 5e-08,
            'theta_int': 2e-06,
        },
        'sigma_refs': {
            'F087.flux': 0.001,
            'F087.rscale': 0.00246,
            'F087.x0': 0.00365,
            'F087.y0': 0.00343,
            'cosi': 0.000956,
            'g1': 0.00112,
            'g2': 0.00117,
            'theta_int': 0.00329,
        },
    },
    'joint_base': {
        'budgets': {
            'F087.flux': 3e-06,
            'F087.rscale': 2e-04,
            'F087.x0': 1e-06,
            'F087.y0': 1e-06,
            'cosi': 8e-04,
            'g1': 6e-06,
            'g2': 2e-03,
            'theta_int': 3e-04,
            'vel.rscale': 2e-02,
            'vel.v0': 3e-05,
            'vel.vcirc': 4e-01,
            'vel.x0': 1e-06,
            'vel.y0': 1e-06,
        },
        'sigma_refs': {
            'F087.flux': 0.001,
            'F087.rscale': 0.00246,
            'F087.x0': 0.00319,
            'F087.y0': 0.00319,
            'cosi': 0.000699,
            'g1': 0.000832,
            'g2': 0.000817,
            'theta_int': 0.000952,
            'vel.rscale': 0.00821,
            'vel.v0': 0.0479,
            'vel.vcirc': 0.205,
            'vel.x0': 0.00496,
            'vel.y0': 0.00452,
        },
    },
    'joint_with_shear': {
        'budgets': {
            'F087.flux': 3e-06,
            'F087.rscale': 2e-04,
            'F087.x0': 3e-06,
            'F087.y0': 2e-06,
            'cosi': 8e-04,
            'g1': 5e-05,
            'g2': 2e-03,
            'theta_int': 1e-04,
            'vel.rscale': 2e-02,
            'vel.v0': 2e-04,
            'vel.vcirc': 4e-01,
            'vel.x0': 5e-04,
            'vel.y0': 3e-04,
        },
        'sigma_refs': {
            'F087.flux': 0.001,
            'F087.rscale': 0.00246,
            'F087.x0': 0.00332,
            'F087.y0': 0.00312,
            'cosi': 0.000698,
            'g1': 0.000825,
            'g2': 0.000804,
            'theta_int': 0.000933,
            'vel.rscale': 0.00815,
            'vel.v0': 0.0474,
            'vel.vcirc': 0.201,
            'vel.x0': 0.00492,
            'vel.y0': 0.00433,
        },
    },
    'inclined_exponential_psf': {
        'budgets': {
            'F087.flux': 3e-06,
            'F087.rscale': 2e-04,
            'F087.x0': 1e-06,
            'F087.y0': 1e-06,
            'cosi': 4e-05,
            'g1': 2e-06,
            'g2': 2e-06,
            'theta_int': 4e-06,
        },
        'sigma_refs': {
            'F087.flux': 0.001,
            'F087.rscale': 0.00249,
            'F087.x0': 0.00362,
            'F087.y0': 0.00362,
            'cosi': 0.000968,
            'g1': 0.00112,
            'g2': 0.00118,
            'theta_int': 0.00332,
        },
    },
    'centered_velocity_psf': {
        'budgets': {
            'cosi': 6e-04,
            'g1': 2e-03,
            'g2': 7e-05,
            'theta_int': 7e-04,
            'vel.rscale': 2e-03,
            'vel.v0': 3e-05,
            'vel.vcirc': 5e-02,
        },
        'sigma_refs': {
            'cosi': 0.00132,
            'g1': 0.00142,
            'g2': 0.00116,
            'theta_int': 0.00105,
            'vel.rscale': 0.00818,
            'vel.v0': 0.0476,
            'vel.vcirc': 0.205,
        },
    },
    'joint_psf': {
        'budgets': {
            'F087.flux': 3e-06,
            'F087.rscale': 2e-04,
            'F087.x0': 1e-06,
            'F087.y0': 1e-06,
            'cosi': 2e-04,
            'g1': 5e-04,
            'g2': 4e-05,
            'theta_int': 6e-04,
            'vel.rscale': 2e-03,
            'vel.v0': 3e-05,
            'vel.vcirc': 5e-02,
            'vel.x0': 1e-06,
            'vel.y0': 1e-06,
        },
        'sigma_refs': {
            'F087.flux': 0.001,
            'F087.rscale': 0.00249,
            'F087.x0': 0.0033,
            'F087.y0': 0.00329,
            'cosi': 0.000707,
            'g1': 0.000845,
            'g2': 0.000829,
            'theta_int': 0.000955,
            'vel.rscale': 0.00818,
            'vel.v0': 0.0476,
            'vel.vcirc': 0.205,
            'vel.x0': 0.00492,
            'vel.y0': 0.00448,
        },
    },
    'centered_vel_masked_aperture': {
        'budgets': {
            'cosi': 4e-03,
            'g1': 7e-05,
            'g2': 3e-03,
            'theta_int': 3e-04,
            'vel.rscale': 2e-02,
            'vel.v0': 3e-05,
            'vel.vcirc': 5e-01,
        },
        'sigma_refs': {
            'cosi': 0.00176,
            'g1': 0.00175,
            'g2': 0.00132,
            'theta_int': 0.00125,
            'vel.rscale': 0.00964,
            'vel.v0': 0.0541,
            'vel.vcirc': 0.257,
        },
    },
    'inclined_exp_masked_aperture': {
        'budgets': {
            'F087.flux': 3e-06,
            'F087.rscale': 2e-04,
            'F087.x0': 1e-06,
            'F087.y0': 1e-06,
            'cosi': 4e-05,
            'g1': 3e-07,
            'g2': 3e-07,
            'theta_int': 2e-06,
        },
        'sigma_refs': {
            'F087.flux': 0.001,
            'F087.rscale': 0.00246,
            'F087.x0': 0.00352,
            'F087.y0': 0.00352,
            'cosi': 0.000958,
            'g1': 0.00111,
            'g2': 0.00119,
            'theta_int': 0.0033,
        },
    },
    'joint_masked': {
        'budgets': {
            'F087.flux': 3e-06,
            'F087.rscale': 2e-04,
            'F087.x0': 1e-06,
            'F087.y0': 1e-06,
            'cosi': 6e-04,
            'g1': 2e-05,
            'g2': 1e-03,
            'theta_int': 2e-04,
            'vel.rscale': 2e-02,
            'vel.v0': 3e-05,
            'vel.vcirc': 5e-01,
            'vel.x0': 1e-06,
            'vel.y0': 1e-06,
        },
        'sigma_refs': {
            'F087.flux': 0.001,
            'F087.rscale': 0.00246,
            'F087.x0': 0.00319,
            'F087.y0': 0.00319,
            'cosi': 0.000746,
            'g1': 0.000896,
            'g2': 0.000879,
            'theta_int': 0.0011,
            'vel.rscale': 0.00964,
            'vel.v0': 0.0541,
            'vel.vcirc': 0.257,
            'vel.x0': 0.00523,
            'vel.y0': 0.00486,
        },
    },
    'inclined_spergel': {
        'budgets': {
            'F087.flux': 3e-06,
            'F087.nu': 2e-05,
            'F087.rscale': 2e-04,
            'F087.x0': 1e-06,
            'F087.y0': 1e-06,
            'cosi': 4e-05,
            'g1': 3e-07,
            'g2': 3e-07,
            'theta_int': 2e-06,
        },
        'sigma_refs': {
            'F087.flux': 0.001,
            'F087.nu': 0.00143,
            'F087.rscale': 0.00246,
            'F087.x0': 0.00352,
            'F087.y0': 0.00352,
            'cosi': 0.000955,
            'g1': 0.00111,
            'g2': 0.00117,
            'theta_int': 0.00328,
        },
    },
    'inclined_spergel_shear': {
        'budgets': {
            'F087.flux': 3e-06,
            'F087.nu': 2e-05,
            'F087.rscale': 2e-04,
            'F087.x0': 1e-06,
            'F087.y0': 1e-06,
            'cosi': 4e-05,
            'g1': 8e-08,
            'g2': 5e-08,
            'theta_int': 2e-06,
        },
        'sigma_refs': {
            'F087.flux': 0.001,
            'F087.nu': 0.00143,
            'F087.rscale': 0.00246,
            'F087.x0': 0.00365,
            'F087.y0': 0.00343,
            'cosi': 0.000956,
            'g1': 0.00112,
            'g2': 0.00117,
            'theta_int': 0.00329,
        },
    },
    'bulge_disk': {
        'budgets': {
            'F087.bulge_frac': 5e-04,
            # bulge_hlr recovery is 4.8e-4 on the production inference grid
            # (measured 2026-07-22), not the ~2e-6 of the untruncated grid the
            # rest of this table was frozen on. Cause: the priors-sized grid
            # caps effective_maxk at psf.maxk, truncating the n=4 emulator FT
            # cusp; the shift is bulge_hlr-dependent and tilts the likelihood
            # peak. The forward model is correct -- the full-grid render
            # recovers truth to 8.8e-7 -- and shear (g1/g2) is unaffected, so
            # this is a nuisance-only grid artifact. Bound set to 1e-3 (2x the
            # measured error), tighter than the 10x rule.
            'F087.bulge_hlr': 1e-03,
            'F087.disk_rscale': 2e-02,
            'F087.total_flux': 4e-03,
            'cosi': 4e-03,
            'g1': 8e-06,
            'g2': 4e-03,
            'theta_int': 8e-05,
        },
        'sigma_refs': {
            'F087.bulge_frac': 3.84e-05,
            'F087.bulge_hlr': 0.000114,
            'F087.disk_rscale': 0.000373,
            'F087.total_flux': 0.0001,
            'cosi': 0.00016,
            'g1': 0.000136,
            'g2': 0.000144,
            'theta_int': 0.000457,
        },
    },
}


# ==============================================================================
# Helper Functions for Synthetic Data
# ==============================================================================


def generate_synthetic_velocity_data(
    model_class,
    true_pars: Dict[str, float],
    image_pars: ImagePars,
    snr: float,
    config: TestConfig,
) -> Tuple[jnp.ndarray, jnp.ndarray, float]:
    """
    Generate synthetic velocity data with noise.

    Parameters
    ----------
    model_class : type
        Velocity model class (e.g., CenteredVelocityModel).
    true_pars : dict
        True parameter values (using model's parameter names).
        Can contain extra parameters that will be filtered out (e.g. joint models).
    image_pars : ImagePars
        Image parameters defining the grid.
    snr : float
        Target signal-to-noise ratio.
    config : TestConfig
        Test configuration.

    Returns
    -------
    data_true : jnp.ndarray
        Noiseless synthetic data.
    data_noisy : jnp.ndarray
        Noisy synthetic data.
    variance : float
        Noise variance used.
    """

    model = model_class()

    # filter parameters to only include those needed by velocity model
    # this is relevant for joint models
    vel_pars = {k: v for k, v in true_pars.items() if k in model.PARAMETER_NAMES}

    theta_true = model.pars2theta(vel_pars)
    X, Y = build_map_grid_from_image_pars(image_pars, unit='arcsec', centered=True)
    data_true = model(theta_true, 'obs', X, Y)

    # Use synthetic module for noise generation
    synth = SyntheticVelocity(vel_pars, model_type='arctan', seed=config.seed)
    data_noisy = synth.generate(image_pars, snr=snr, seed=config.seed)
    variance = synth.variance
    data_true = synth.data_true  # Use synthetic's version for consistency

    return data_true, data_noisy, variance


def generate_synthetic_intensity_data(
    model_class,
    true_pars: Dict[str, float],
    image_pars: ImagePars,
    snr: float,
    config: TestConfig,
    model_type: str = 'exponential',
) -> Tuple[jnp.ndarray, jnp.ndarray, float]:
    """
    Generate synthetic intensity data with noise.

    Parameters
    ----------
    model_class : type
        Intensity model class (e.g., InclinedExponentialModel).
    true_pars : dict
        True parameter values (using model's parameter names).
    image_pars : ImagePars
        Image parameters defining the grid.
    snr : float
        Target signal-to-noise ratio.
    config : TestConfig
        Test configuration.
    model_type : str, optional
        Synthetic model type ('exponential' or 'spergel'). Default 'exponential'.

    Returns
    -------
    data_true, data_noisy, variance
    """

    model = model_class()

    # filter parameters to only include those needed by intensity model
    int_pars = {k: v for k, v in true_pars.items() if k in model.PARAMETER_NAMES}

    theta_true = model.pars2theta(int_pars)
    X, Y = build_map_grid_from_image_pars(image_pars, unit='arcsec', centered=True)
    data_true = model(theta_true, 'obs', X, Y)

    # Use synthetic module for noise generation
    synth = SyntheticIntensity(int_pars, model_type=model_type, seed=config.seed)
    data_noisy = synth.generate(
        image_pars,
        snr=snr,
        seed=config.seed,
        include_poisson=config.include_poisson_noise,
        sersic_backend=config.sersic_backend,
    )
    variance = synth.variance
    data_true = synth.data_true

    return data_true, data_noisy, variance


# ==============================================================================
# Test: Centered Velocity Model (Base Case)
# ==============================================================================


def test_recover_centered_velocity_base(test_config, velocity_grids, snr=1000):
    """
    Test parameter recovery for CenteredVelocityModel (arctan rotation curve).

    Base case: no centroid offset, no shear.

    This is the simplest test case and serves as a sanity check that:
    - The forward model produces sensible velocity fields
    - The likelihood function is well-behaved
    - Parameters can be recovered in principle
    """

    X, Y = velocity_grids

    # Flat-key dict for SyntheticVelocity. CenteredVelocityModel has no
    # centroid parameters, so none appear here or in the priors (sampling
    # them produced a perfectly flat likelihood the curvature gate rejects).
    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
    }

    vel_model = CenteredVelocityModel()
    source = SourceModel(velocity_model=vel_model)

    data_true, data_noisy, variance = generate_synthetic_velocity_data(
        CenteredVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )

    # Diagnostic plot of truth via SourceModel render
    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    model_eval = np.asarray(source.render_velocity(pars_dotted, obs_vel_noPSF))

    test_name = "centered_velocity_base"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity, data=data_true, variance=variance
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, velocity_obs=obs_vel)
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_velocity,
    )

    recovery_stats = plot_likelihood_slices(
        slices, pars_dotted, test_name, test_config, snr, 'velocity'
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['centered_velocity_base'],
        test_name='Centered velocity (base)',
    )


# ==============================================================================
# Test: Centered Velocity Model with Shear
# ==============================================================================


def test_recover_centered_velocity_with_shear(test_config, velocity_grids, snr=1000):
    """
    Test parameter recovery with non-zero shear.

    This test verifies g1 and g2 can be recovered along with kinematic parameters.
    """

    X, Y = velocity_grids

    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.05,
        'g2': -0.03,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.05,
        'g2': -0.03,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
    }

    vel_model = CenteredVelocityModel()
    source = SourceModel(velocity_model=vel_model)

    data_true, data_noisy, variance = generate_synthetic_velocity_data(
        CenteredVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )

    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    model_eval = np.asarray(source.render_velocity(pars_dotted, obs_vel_noPSF))

    test_name = "centered_velocity_with_shear"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity, data=data_true, variance=variance
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, velocity_obs=obs_vel)
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_velocity,
    )

    recovery_stats = plot_likelihood_slices(
        slices, pars_dotted, test_name, test_config, snr, 'velocity'
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['centered_velocity_with_shear'],
        test_name='Centered velocity (w/ shear)',
    )


# ==============================================================================
# Test: Offset Velocity Model
# ==============================================================================


def test_recover_offset_velocity(test_config, velocity_grids, snr=1000):
    """
    Test parameter recovery for OffsetVelocityModel.

    Includes centroid offsets (x0, y0) in addition to kinematic parameters.
    This tests our ability to recover spatial offsets along with velocities.
    """

    X, Y = velocity_grids

    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.02,
        'g2': -0.01,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
        'x0': 1.5,
        'y0': -1.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.02,
        'g2': -0.01,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
        'vel.x0': 1.5,
        'vel.y0': -1.0,
    }

    vel_model = OffsetVelocityModel()
    source = SourceModel(velocity_model=vel_model)

    data_true, data_noisy, variance = generate_synthetic_velocity_data(
        OffsetVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )

    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    model_eval = np.asarray(source.render_velocity(pars_dotted, obs_vel_noPSF))

    test_name = "offset_velocity"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity, data=data_true, variance=variance
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
        'vel.x0': Uniform(-5.0, 5.0),
        'vel.y0': Uniform(-5.0, 5.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, velocity_obs=obs_vel)
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_velocity,
    )

    recovery_stats = plot_likelihood_slices(
        slices, pars_dotted, test_name, test_config, snr, 'velocity'
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['offset_velocity'],
        test_name='Offset velocity',
    )


# ==============================================================================
# Test: Inclined Exponential Intensity Model (Base Case)
# ==============================================================================


def test_recover_inclined_exponential(test_config, intensity_grids, snr=1000):
    """Test parameter recovery for InclinedExponentialModel."""

    X, Y = intensity_grids

    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    int_model = InclinedExponentialModel()
    source = SourceModel(broadband_models={'F087': int_model})

    data_true, data_noisy, variance = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        true_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
    )

    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_eval = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )

    test_name = "inclined_exponential"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_true,
        variance=variance,
        broadband_key='F087',
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-5.0, 5.0),
        'F087.y0': Uniform(-5.0, 5.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_intensity,
    )

    recovery_stats = plot_likelihood_slices(
        slices, pars_dotted, test_name, test_config, snr, 'intensity'
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['inclined_exponential'],
        test_name='Inclined exponential (base)',
    )


# ==============================================================================
# Test: Inclined Exponential with Shear
# ==============================================================================


def test_recover_inclined_exponential_with_shear(
    test_config, intensity_grids, snr=1000
):
    """Test parameter recovery for InclinedExponentialModel with shear."""

    X, Y = intensity_grids

    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    int_model = InclinedExponentialModel()
    source = SourceModel(broadband_models={'F087': int_model})

    data_true, data_noisy, variance = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        true_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
    )

    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_eval = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )

    test_name = "inclined_exponential_with_shear"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_true,
        variance=variance,
        broadband_key='F087',
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-5.0, 5.0),
        'F087.y0': Uniform(-5.0, 5.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_intensity,
    )

    recovery_stats = plot_likelihood_slices(
        slices, pars_dotted, test_name, test_config, snr, 'intensity'
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['inclined_exponential_with_shear'],
        test_name='Inclined exponential (w/ shear)',
    )


# ==============================================================================
# Test: Joint Model (Base Case)
# ==============================================================================


def test_recover_joint_base(test_config, velocity_grids, intensity_grids, snr=1000):
    """
    Test parameter recovery for joint velocity + intensity model.

    Base case: no shear, centered galaxy. This tests the ability to
    simultaneously constrain kinematic and morphological parameters.
    """

    X_vel, Y_vel = velocity_grids
    X_int, Y_int = intensity_grids

    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
        'x0': 0.0,
        'y0': 0.0,
    }
    int_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
        'vel.x0': 0.0,
        'vel.y0': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    vel_model = OffsetVelocityModel()
    int_model = InclinedExponentialModel()
    source = SourceModel(
        velocity_model=vel_model,
        broadband_models={'F087': int_model},
    )

    data_vel_true, data_vel_noisy, variance_vel = generate_synthetic_velocity_data(
        OffsetVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )
    data_int_true, data_int_noisy, variance_int = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        int_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
    )

    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_vel_eval = np.asarray(source.render_velocity(pars_dotted, obs_vel_noPSF))
    model_int_eval = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )

    test_name = "joint_base"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_vel_noisy),
        data_true=np.asarray(data_vel_true),
        model_eval=model_vel_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance_vel,
        n_params=9,
        enable_plots=test_config.enable_plots,
    )
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_int_noisy),
        data_true=np.asarray(data_int_true),
        model_eval=model_int_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance_int,
        n_params=9,
        enable_plots=test_config.enable_plots,
    )

    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity,
        data=data_vel_true,
        variance=variance_vel,
    )
    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_int_true,
        variance=variance_int,
        broadband_key='F087',
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
        'vel.x0': Uniform(-5.0, 5.0),
        'vel.y0': Uniform(-5.0, 5.0),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-5.0, 5.0),
        'F087.y0': Uniform(-5.0, 5.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(
        source, priors, velocity_obs=obs_vel, image_obs={'F087': obs_int}
    )
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=None,
    )

    recovery_stats = plot_likelihood_slices(
        slices, pars_dotted, test_name, test_config, snr, 'joint'
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['joint_base'],
        test_name='Joint model (base)',
    )


# ==============================================================================
# Test: Joint Model with Shear
# ==============================================================================


def test_recover_joint_with_shear(
    test_config, velocity_grids, intensity_grids, snr=1000
):
    """
    Test parameter recovery for joint model with non-zero shear.

    This is the most comprehensive test, combining kinematic and morphological
    information to constrain shear along with all other parameters.
    """

    X_vel, Y_vel = velocity_grids
    X_int, Y_int = intensity_grids

    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
        'x0': 1.0,
        'y0': -0.5,
    }
    int_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 1.0,
        'y0': -0.5,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
        'vel.x0': 1.0,
        'vel.y0': -0.5,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 1.0,
        'F087.y0': -0.5,
    }

    vel_model = OffsetVelocityModel()
    int_model = InclinedExponentialModel()
    source = SourceModel(
        velocity_model=vel_model,
        broadband_models={'F087': int_model},
    )

    data_vel_true, data_vel_noisy, variance_vel = generate_synthetic_velocity_data(
        OffsetVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )
    data_int_true, data_int_noisy, variance_int = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        int_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
    )

    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_vel_eval = np.asarray(source.render_velocity(pars_dotted, obs_vel_noPSF))
    model_int_eval = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )

    test_name = "joint_with_shear"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_vel_noisy),
        data_true=np.asarray(data_vel_true),
        model_eval=model_vel_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance_vel,
        n_params=9,
        enable_plots=test_config.enable_plots,
    )
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_int_noisy),
        data_true=np.asarray(data_int_true),
        model_eval=model_int_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance_int,
        n_params=9,
        enable_plots=test_config.enable_plots,
    )

    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity,
        data=data_vel_true,
        variance=variance_vel,
    )
    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_int_true,
        variance=variance_int,
        broadband_key='F087',
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
        'vel.x0': Uniform(-5.0, 5.0),
        'vel.y0': Uniform(-5.0, 5.0),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-5.0, 5.0),
        'F087.y0': Uniform(-5.0, 5.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(
        source, priors, velocity_obs=obs_vel, image_obs={'F087': obs_int}
    )
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=None,
    )

    recovery_stats = plot_likelihood_slices(
        slices, pars_dotted, test_name, test_config, snr, 'joint'
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['joint_with_shear'],
        test_name='Joint model (w/ shear)',
    )


# ==============================================================================
# Test: Inclined Exponential with PSF
# ==============================================================================


def test_recover_inclined_exponential_with_psf(test_config, intensity_grids):
    """Test parameter recovery for InclinedExponentialModel with PSF at SNR=1000."""
    import galsim as gs

    snr = 1000
    X, Y = intensity_grids

    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    psf = gs.Gaussian(fwhm=0.625)

    from kl_pipe.synthetic import SyntheticIntensity

    synth = SyntheticIntensity(
        true_pars_flat, model_type='exponential', seed=test_config.seed, psf=psf
    )
    data_noisy = synth.generate(
        test_config.image_pars_intensity,
        snr=snr,
        seed=test_config.seed,
        include_poisson=test_config.include_poisson_noise,
        sersic_backend='galsim',
    )
    variance = synth.variance
    data_true = synth.data_true

    int_model = InclinedExponentialModel()
    source = SourceModel(broadband_models={'F087': int_model})

    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        psf=psf,
        data=data_true,
        variance=variance,
        int_model=int_model,
        broadband_key='F087',
    )

    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-5.0, 5.0),
        'F087.y0': Uniform(-5.0, 5.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_intensity,
    )

    test_name = "inclined_exponential_psf"
    recovery_stats = plot_likelihood_slices(
        slices,
        pars_dotted,
        test_name,
        test_config,
        snr,
        'intensity',
        has_psf=True,
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['inclined_exponential_psf'],
        test_name='Inclined exponential (PSF)',
    )


# ==============================================================================
# Test: Centered Velocity with PSF
# ==============================================================================


def test_recover_centered_velocity_with_psf(test_config, velocity_grids):
    """Test parameter recovery for CenteredVelocityModel with PSF at SNR=1000.

    The velocity PSF is flux-weighted by an emission-line intensity (Halpha)
    via ``VelocityObs.flux_weight_key='Halpha'``. The Halpha intensity is
    fixed at truth in the prior dict; only the velocity + shared-geometry
    parameters are sampled.
    """
    import galsim as gs

    snr = 1000
    X, Y = velocity_grids

    # Flat dicts for synthetic data generation (bare-model API).
    true_pars_vel_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
    }
    true_pars_int_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    # Full SourceModel dotted dict (used for fixed-pars + slice labelling).
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
        'Halpha.flux': 1.0,
        'Halpha.rscale': 3.0,
        'Halpha.h_over_r': 0.1,
        'Halpha.x0': 0.0,
        'Halpha.y0': 0.0,
    }

    psf = gs.Gaussian(fwhm=0.625)

    # noiseless intensity for flux weighting (on velocity grid)
    from kl_pipe.synthetic import generate_sersic_intensity_2d

    flux_image = generate_sersic_intensity_2d(
        test_config.image_pars_velocity,
        backend='scipy',
        n_sersic=1.0,
        **{k: v for k, v in true_pars_int_flat.items() if k != 'n_sersic'},
    )

    # PSF-convolved velocity data
    from kl_pipe.synthetic import SyntheticVelocity

    synth = SyntheticVelocity(
        true_pars_vel_flat,
        model_type='arctan',
        seed=test_config.seed,
        psf=psf,
        intensity_for_psf=flux_image,
    )
    data_noisy = synth.generate(
        test_config.image_pars_velocity,
        snr=snr,
        seed=test_config.seed,
    )
    variance = synth.variance

    # SourceModel: CenteredVelocity + Halpha line for flux weighting
    vel_model = CenteredVelocityModel()
    halpha_int = InclinedExponentialModel()
    source = SourceModel(
        velocity_model=vel_model,
        emission_lines={'Halpha': EmissionLine(intensity=halpha_int)},
    )

    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity,
        psf=psf,
        data=synth.data_true,
        variance=variance,
        flux_weight_key='Halpha',
    )

    # Sample velocity + shared-geometry params; fix Halpha params at truth.
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
        'Halpha.flux': 1.0,  # fixed (drives PSF weight only)
        'Halpha.rscale': 3.0,  # fixed
        'Halpha.h_over_r': 0.1,  # fixed
        'Halpha.x0': 0.0,  # fixed
        'Halpha.y0': 0.0,  # fixed
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, velocity_obs=obs_vel)
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_velocity,
    )

    test_name = "centered_velocity_psf"
    recovery_stats = plot_likelihood_slices(
        slices,
        pars_dotted,
        test_name,
        test_config,
        snr,
        'velocity',
        has_psf=True,
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['centered_velocity_psf'],
        test_name='Centered velocity (PSF)',
    )


# ==============================================================================
# Test: Joint Model with PSF
# ==============================================================================


def test_recover_joint_with_psf(test_config, velocity_grids, intensity_grids):
    """Test parameter recovery for joint vel+phot model with PSF at SNR=1000.

    Velocity PSF weighting uses an Halpha emission line whose spatial
    profile is fixed equal to the F087 broadband truth in the prior dict.
    """
    import galsim as gs

    snr = 1000
    X_vel, Y_vel = velocity_grids
    X_int, Y_int = intensity_grids

    # Flat-key dict for synthetic data (bare-model API).
    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
        'x0': 0.0,
        'y0': 0.0,
    }
    int_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
        'vel.x0': 0.0,
        'vel.y0': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
        # Halpha line carries the spatial profile for velocity-PSF weighting.
        # Truth identical to F087 broadband so weight = broadband intensity.
        'Halpha.flux': 1.0,
        'Halpha.rscale': 3.0,
        'Halpha.h_over_r': 0.1,
        'Halpha.x0': 0.0,
        'Halpha.y0': 0.0,
    }

    psf = gs.Gaussian(fwhm=0.625)

    from kl_pipe.synthetic import (
        SyntheticIntensity,
        SyntheticVelocity,
        generate_sersic_intensity_2d,
    )

    synth_int = SyntheticIntensity(
        {
            k: v
            for k, v in int_pars_flat.items()
            if k in InclinedExponentialModel.PARAMETER_NAMES
        },
        model_type='exponential',
        seed=test_config.seed,
        psf=psf,
    )
    data_int_noisy = synth_int.generate(
        test_config.image_pars_intensity,
        snr=snr,
        seed=test_config.seed,
        include_poisson=test_config.include_poisson_noise,
        sersic_backend='galsim',
    )
    variance_int = synth_int.variance

    int_pars_for_vel = {
        k: v
        for k, v in int_pars_flat.items()
        if k in InclinedExponentialModel.PARAMETER_NAMES
    }
    flux_image = generate_sersic_intensity_2d(
        test_config.image_pars_velocity,
        backend='scipy',
        n_sersic=1.0,
        **{k: v for k, v in int_pars_for_vel.items() if k != 'n_sersic'},
    )

    synth_vel = SyntheticVelocity(
        {
            k: v
            for k, v in true_pars_flat.items()
            if k in OffsetVelocityModel.PARAMETER_NAMES
        },
        model_type='arctan',
        seed=test_config.seed + 1,
        psf=psf,
        intensity_for_psf=flux_image,
    )
    data_vel_noisy = synth_vel.generate(
        test_config.image_pars_velocity,
        snr=snr,
        seed=test_config.seed + 1,
    )
    variance_vel = synth_vel.variance

    # SourceModel: OffsetVelocity + F087 broadband + Halpha line for flux weight
    vel_model = OffsetVelocityModel()
    f087_int = InclinedExponentialModel()
    halpha_int = InclinedExponentialModel()
    source = SourceModel(
        velocity_model=vel_model,
        broadband_models={'F087': f087_int},
        emission_lines={'Halpha': EmissionLine(intensity=halpha_int)},
    )

    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity,
        psf=psf,
        data=synth_vel.data_true,
        variance=variance_vel,
        flux_weight_key='Halpha',
    )
    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        psf=psf,
        data=synth_int.data_true,
        variance=variance_int,
        int_model=f087_int,
        broadband_key='F087',
    )

    # Sample shared geo + vel + F087 (excluding F087.h_over_r); fix Halpha at truth.
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
        'vel.x0': Uniform(-5.0, 5.0),
        'vel.y0': Uniform(-5.0, 5.0),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-5.0, 5.0),
        'F087.y0': Uniform(-5.0, 5.0),
        # Halpha spatial profile fixed at truth (drives velocity-PSF weight)
        'Halpha.flux': 1.0,
        'Halpha.rscale': 3.0,
        'Halpha.h_over_r': 0.1,
        'Halpha.x0': 0.0,
        'Halpha.y0': 0.0,
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(
        source, priors, velocity_obs=obs_vel, image_obs={'F087': obs_int}
    )
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=None,
    )

    test_name = "joint_psf"
    recovery_stats = plot_likelihood_slices(
        slices,
        pars_dotted,
        test_name,
        test_config,
        snr,
        'joint',
        has_psf=True,
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['joint_psf'],
        test_name='Joint model (PSF)',
    )


# ==============================================================================
# Tests: Mask Support
# ==============================================================================


def _vel_priors_for_invariance(true_pars_dotted):
    """Uniform priors centered at truth for the invariance-test SourceModel.

    Every velocity param gets a small Uniform so the sampled-names vector
    is non-empty and ``task.likelihood_fn`` evaluates at the truth values.
    """
    sampled = {}
    for k, v in true_pars_dotted.items():
        # all params get a tight Uniform around truth (placeholder for sampling)
        sampled[k] = Uniform(v - 1.0, v + 1.0) if v != 0.0 else Uniform(-0.5, 0.5)
    return PriorDict(sampled)


def _int_priors_for_invariance(true_pars_dotted):
    sampled = {}
    for k, v in true_pars_dotted.items():
        if k.endswith('h_over_r'):
            sampled[k] = v  # fixed
        elif k == 'cosi':
            # physical cosi range (0, 1]; the wide v +/- 1 default would reach
            # edge-on, which the intensity-task guard rejects. these invariance
            # tests evaluate logL at the truth, so the exact bounds are immaterial.
            sampled[k] = Uniform(0.05, 0.99)
        else:
            sampled[k] = Uniform(v - 1.0, v + 1.0) if v != 0.0 else Uniform(-0.5, 0.5)
    return PriorDict(sampled)


def _vel_invariance_loglike(image_pars, data, variance, true_pars_dotted, mask):
    """Build a SourceModel velocity task and return log_like(theta_truth)."""
    obs = build_velocity_obs(image_pars, data=data, variance=variance, mask=mask)
    source = SourceModel(velocity_model=CenteredVelocityModel())
    priors = _vel_priors_for_invariance(true_pars_dotted)
    task = InferenceTask.from_obs(source, priors, velocity_obs=obs)
    theta = jnp.array([true_pars_dotted[n] for n in priors.sampled_names])
    return float(task.likelihood_fn(theta))


def _int_invariance_loglike(image_pars, data, variance, true_pars_dotted, mask):
    """Build a SourceModel broadband task and return log_like(theta_truth)."""
    obs = build_image_obs(
        image_pars, data=data, variance=variance, mask=mask, broadband_key='F087'
    )
    source = SourceModel(broadband_models={'F087': InclinedExponentialModel()})
    priors = _int_priors_for_invariance(true_pars_dotted)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs})
    theta = jnp.array([true_pars_dotted[n] for n in priors.sampled_names])
    return float(task.likelihood_fn(theta))


_VEL_INVARIANCE_TRUTH_FLAT = {
    'cosi': 0.6,
    'theta_int': 0.785,
    'g1': 0.0,
    'g2': 0.0,
    'v0': 10.0,
    'vcirc': 200.0,
    'rscale': 5.0,
}
_VEL_INVARIANCE_TRUTH_DOTTED = {
    'cosi': 0.6,
    'theta_int': 0.785,
    'g1': 0.0,
    'g2': 0.0,
    'vel.v0': 10.0,
    'vel.vcirc': 200.0,
    'vel.rscale': 5.0,
}

_INT_INVARIANCE_TRUTH_FLAT = {
    'cosi': 0.7,
    'theta_int': 0.785,
    'g1': 0.0,
    'g2': 0.0,
    'flux': 1.0,
    'rscale': 3.0,
    'h_over_r': 0.1,
    'x0': 0.0,
    'y0': 0.0,
}
_INT_INVARIANCE_TRUTH_DOTTED = {
    'cosi': 0.7,
    'theta_int': 0.785,
    'g1': 0.0,
    'g2': 0.0,
    'F087.flux': 1.0,
    'F087.rscale': 3.0,
    'F087.h_over_r': 0.1,
    'F087.x0': 0.0,
    'F087.y0': 0.0,
}


def test_mask_none_matches_unmasked_velocity(test_config):
    """mask_vel=None gives identical logL to omitting mask entirely."""
    _, data_noisy, variance = generate_synthetic_velocity_data(
        CenteredVelocityModel,
        _VEL_INVARIANCE_TRUTH_FLAT,
        test_config.image_pars_velocity,
        1000,
        test_config,
    )

    val1 = _vel_invariance_loglike(
        test_config.image_pars_velocity,
        data_noisy,
        variance,
        _VEL_INVARIANCE_TRUTH_DOTTED,
        mask=None,
    )
    val2 = _vel_invariance_loglike(
        test_config.image_pars_velocity,
        data_noisy,
        variance,
        _VEL_INVARIANCE_TRUTH_DOTTED,
        mask=None,
    )
    assert val1 == val2, f"mask=None differs from no mask: {val1} vs {val2}"


def test_all_true_mask_matches_unmasked_velocity(test_config):
    """All-True mask gives same logL as no mask."""
    _, data_noisy, variance = generate_synthetic_velocity_data(
        CenteredVelocityModel,
        _VEL_INVARIANCE_TRUTH_FLAT,
        test_config.image_pars_velocity,
        1000,
        test_config,
    )

    all_true = jnp.ones(data_noisy.shape, dtype=bool)
    val1 = _vel_invariance_loglike(
        test_config.image_pars_velocity,
        data_noisy,
        variance,
        _VEL_INVARIANCE_TRUTH_DOTTED,
        mask=None,
    )
    val2 = _vel_invariance_loglike(
        test_config.image_pars_velocity,
        data_noisy,
        variance,
        _VEL_INVARIANCE_TRUTH_DOTTED,
        mask=all_true,
    )
    np.testing.assert_allclose(
        val1, val2, rtol=1e-6, err_msg="All-True mask should match no mask"
    )


def test_mask_none_matches_unmasked_intensity(test_config):
    """mask_int=None gives identical logL to omitting mask entirely."""
    _, data_noisy, variance = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        _INT_INVARIANCE_TRUTH_FLAT,
        test_config.image_pars_intensity,
        1000,
        test_config,
    )

    val1 = _int_invariance_loglike(
        test_config.image_pars_intensity,
        data_noisy,
        variance,
        _INT_INVARIANCE_TRUTH_DOTTED,
        mask=None,
    )
    val2 = _int_invariance_loglike(
        test_config.image_pars_intensity,
        data_noisy,
        variance,
        _INT_INVARIANCE_TRUTH_DOTTED,
        mask=None,
    )
    assert val1 == val2, f"mask=None differs from no mask: {val1} vs {val2}"


def test_all_true_mask_matches_unmasked_intensity(test_config):
    """All-True mask gives same logL as no mask."""
    _, data_noisy, variance = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        _INT_INVARIANCE_TRUTH_FLAT,
        test_config.image_pars_intensity,
        1000,
        test_config,
    )

    all_true = jnp.ones(data_noisy.shape, dtype=bool)
    val1 = _int_invariance_loglike(
        test_config.image_pars_intensity,
        data_noisy,
        variance,
        _INT_INVARIANCE_TRUTH_DOTTED,
        mask=None,
    )
    val2 = _int_invariance_loglike(
        test_config.image_pars_intensity,
        data_noisy,
        variance,
        _INT_INVARIANCE_TRUTH_DOTTED,
        mask=all_true,
    )
    np.testing.assert_allclose(
        val1, val2, rtol=1e-6, err_msg="All-True mask should match no mask"
    )


def test_masked_likelihood_gradient_velocity(test_config):
    """jax.grad through masked likelihood produces finite, non-zero gradients."""
    import jax

    _, data_noisy, variance = generate_synthetic_velocity_data(
        CenteredVelocityModel,
        _VEL_INVARIANCE_TRUTH_FLAT,
        test_config.image_pars_velocity,
        1000,
        test_config,
    )

    mask = make_aperture_mask(data_noisy.shape)
    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity,
        data=data_noisy,
        variance=variance,
        mask=jnp.array(mask),
    )
    source = SourceModel(velocity_model=CenteredVelocityModel())
    priors = _vel_priors_for_invariance(_VEL_INVARIANCE_TRUTH_DOTTED)
    task = InferenceTask.from_obs(source, priors, velocity_obs=obs_vel)

    theta_true = jnp.array(
        [_VEL_INVARIANCE_TRUTH_DOTTED[n] for n in priors.sampled_names]
    )
    grad_fn = jax.grad(task.likelihood_fn)
    grad = grad_fn(theta_true)

    assert jnp.all(jnp.isfinite(grad)), f"Non-finite gradients: {grad}"
    assert jnp.any(grad != 0.0), f"All-zero gradients: {grad}"


def test_recover_centered_velocity_masked_aperture(test_config, velocity_grids):
    """Recovery with elliptical aperture mask at SNR=1000."""
    X, Y = velocity_grids
    snr = 1000

    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
    }

    vel_model = CenteredVelocityModel()
    source = SourceModel(velocity_model=vel_model)

    data_true, data_noisy, variance = generate_synthetic_velocity_data(
        CenteredVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )

    mask = make_aperture_mask(data_noisy.shape)

    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    model_eval = np.asarray(source.render_velocity(pars_dotted, obs_vel_noPSF))
    test_name = "centered_vel_masked_aperture"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
        mask=mask,
    )

    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity,
        data=data_true,
        variance=variance,
        mask=jnp.array(mask),
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, velocity_obs=obs_vel)
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_velocity,
    )

    recovery_stats = plot_likelihood_slices(
        slices,
        pars_dotted,
        test_name,
        test_config,
        snr,
        'velocity',
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['centered_vel_masked_aperture'],
        test_name='Centered velocity (masked aperture)',
    )


def test_recover_inclined_exponential_masked_aperture(test_config, intensity_grids):
    """Recovery with elliptical aperture mask at SNR=1000."""
    X, Y = intensity_grids
    snr = 1000

    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    int_model = InclinedExponentialModel()
    source = SourceModel(broadband_models={'F087': int_model})

    data_true, data_noisy, variance = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        true_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
    )

    mask = make_aperture_mask(data_noisy.shape)

    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_eval = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )
    test_name = "inclined_exp_masked_aperture"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
        mask=mask,
    )

    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_true,
        variance=variance,
        mask=jnp.array(mask),
        broadband_key='F087',
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-5.0, 5.0),
        'F087.y0': Uniform(-5.0, 5.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_intensity,
    )
    recovery_stats = plot_likelihood_slices(
        slices,
        pars_dotted,
        test_name,
        test_config,
        snr,
        'intensity',
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['inclined_exp_masked_aperture'],
        test_name='Inclined exponential (masked aperture)',
    )


def test_recover_joint_masked(test_config, velocity_grids, intensity_grids):
    """Joint likelihood slice recovery with both masks at SNR=1000."""
    X_vel, Y_vel = velocity_grids
    X_int, Y_int = intensity_grids
    snr = 1000

    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
        'x0': 0.0,
        'y0': 0.0,
    }
    int_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
        'vel.x0': 0.0,
        'vel.y0': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    vel_model = OffsetVelocityModel()
    int_model = InclinedExponentialModel()
    source = SourceModel(
        velocity_model=vel_model,
        broadband_models={'F087': int_model},
    )

    data_vel_true, data_vel_noisy, variance_vel = generate_synthetic_velocity_data(
        OffsetVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )
    data_int_true, data_int_noisy, variance_int = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        int_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
    )

    mask_vel = make_aperture_mask(data_vel_noisy.shape)
    mask_int = make_aperture_mask(data_int_noisy.shape)

    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_vel_eval = np.asarray(source.render_velocity(pars_dotted, obs_vel_noPSF))
    model_int_eval = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )

    test_name = "joint_masked"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_vel_noisy),
        data_true=np.asarray(data_vel_true),
        model_eval=model_vel_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance_vel,
        n_params=9,
        enable_plots=test_config.enable_plots,
        mask=mask_vel,
    )
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_int_noisy),
        data_true=np.asarray(data_int_true),
        model_eval=model_int_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance_int,
        n_params=9,
        enable_plots=test_config.enable_plots,
        mask=mask_int,
    )

    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity,
        data=data_vel_true,
        variance=variance_vel,
        mask=jnp.array(mask_vel),
    )
    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_int_true,
        variance=variance_int,
        mask=jnp.array(mask_int),
        broadband_key='F087',
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
        'vel.x0': Uniform(-5.0, 5.0),
        'vel.y0': Uniform(-5.0, 5.0),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-5.0, 5.0),
        'F087.y0': Uniform(-5.0, 5.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(
        source, priors, velocity_obs=obs_vel, image_obs={'F087': obs_int}
    )
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=None,
    )

    recovery_stats = plot_likelihood_slices(
        slices,
        pars_dotted,
        test_name,
        test_config,
        snr,
        'joint',
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['joint_masked'],
        test_name='Joint model (masked)',
    )


# ==============================================================================
# Spergel Intensity Model Recovery
# ==============================================================================


def _run_spergel_slice_test(
    test_config,
    gates_key,
    true_pars_flat,
    pars_dotted,
    test_name,
    label,
    snr,
    nu_low=-0.5,
    nu_high=4.0,
):
    """Shared body for the Spergel slice recovery tests.

    nu_low / nu_high define the nu prior. The default keeps clear of the
    inclined-cusp regime that SourceModel's check_priors_safe rejects when
    cosi is also free; the de Vauc variant overrides them since nu = -0.6
    is exactly on the cusp side and the test asserts recovery there.
    """
    int_model = InclinedSpergelModel()
    source = SourceModel(broadband_models={'F087': int_model})

    data_true, data_noisy, variance = generate_synthetic_intensity_data(
        InclinedSpergelModel,
        true_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
        model_type='spergel',
    )

    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_eval = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )

    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_true,
        variance=variance,
        broadband_key='F087',
    )

    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.nu': Uniform(nu_low, nu_high),
        'F087.x0': Uniform(-5.0, 5.0),
        'F087.y0': Uniform(-5.0, 5.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_intensity,
    )

    recovery_stats = plot_likelihood_slices(
        slices, pars_dotted, test_name, test_config, snr, 'intensity'
    )

    assert_noiseless_gates(recovery_stats, slices, **_GATES[gates_key], test_name=label)


def test_recover_inclined_spergel(test_config, intensity_grids, snr=1000):
    """Test parameter recovery for InclinedSpergelModel (nu=0.5)."""
    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'nu': 0.5,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.nu': 0.5,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }
    _run_spergel_slice_test(
        test_config,
        'inclined_spergel',
        true_pars_flat,
        pars_dotted,
        test_name="inclined_spergel",
        label='Inclined Spergel (base)',
        snr=snr,
    )


@pytest.mark.skip(
    reason=(
        "InclinedSpergelModel renders inaccurately at nu < -0.5 + cosi < 0.9 "
        "(documented cusp issue, see InclinedSpergelModel class docstring). "
        "The check_priors_safe guard rejects this combination at task "
        "construction. PSF damping does not save the rendering: PSF FWHM "
        "(~1.6 pixels) is much smaller than the cusp spread along the minor "
        "axis (~5 pixels). Empirically the scipy synthetic vs k-space model "
        "paths disagree by ~20-25% at the cusp, even with matched PSF on both "
        "sides. Un-skip after the InclinedSpergelModel renderer is fixed for "
        "the inclined-cusp regime, or after a renderer alternative is wired in."
    )
)
@pytest.mark.parametrize("snr", [10000, 1000])
def test_recover_inclined_spergel_devac(snr, test_config, intensity_grids):
    """Test parameter recovery for InclinedSpergelModel (nu=-0.6, de Vaucouleurs).

    Validates the Spergel-as-de-Vauc inference pathway at inclined
    orientation. Currently skipped (see decorator); test body is
    SourceModel-native so it's ready to run once the renderer limitation
    is resolved.
    """
    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 1.5,
        'h_over_r': 0.1,
        'nu': -0.6,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 1.5,
        'F087.h_over_r': 0.1,
        'F087.nu': -0.6,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    int_model = InclinedSpergelModel()
    source = SourceModel(broadband_models={'F087': int_model})

    data_true, data_noisy, variance = generate_synthetic_intensity_data(
        InclinedSpergelModel,
        true_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
        model_type='spergel',
    )

    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_eval = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )

    test_name = f"inclined_spergel_devac_snr{snr}"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_noisy,
        variance=variance,
        broadband_key='F087',
    )

    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.nu': Uniform(-0.85, 4.0),
        'F087.x0': Uniform(-5.0, 5.0),
        'F087.y0': Uniform(-5.0, 5.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=test_config.image_pars_intensity,
    )

    recovery_stats = plot_likelihood_slices(
        slices, pars_dotted, test_name, test_config, snr, 'intensity'
    )

    assert_parameter_recovery(recovery_stats, snr, 'Inclined Spergel (de Vauc)')


def test_recover_inclined_spergel_with_shear(test_config, intensity_grids, snr=1000):
    """Test parameter recovery for InclinedSpergelModel with shear."""
    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'nu': 0.5,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.nu': 0.5,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }
    _run_spergel_slice_test(
        test_config,
        'inclined_spergel_shear',
        true_pars_flat,
        pars_dotted,
        test_name="inclined_spergel_shear",
        label='Inclined Spergel (w/ shear)',
        snr=snr,
    )


# ==============================================================================
# Test: Joint Vel + Broadband + Grism (line) Likelihood Slice
# ==============================================================================


# Nominal noise convention for the joint phot+grism test below: variances
# are set as if the data had matched-filter SNR=1000, which normalizes the
# error-bar references. The data itself is noise-free.
_JOINT_GRISM_SNR = 1000

# Accuracy budgets for noise-free recovery (absolute, parameter units).
# Rule: 10x the recovery error measured on this frozen scene (2026-07-08),
# floored at 1e-5 of the scan half-range against numerical drift, rounded
# up to one significant figure. Broadband-driven parameters bound the
# k-space renderer against GalSim-rendered data; grism-driven parameters
# bound the forward model and estimator directly.
_JOINT_GRISM_BUDGETS = {
    'cosi': 3e-5,
    'theta_int': 2e-6,
    'g1': 3e-7,
    'g2': 3e-5,
    'vel.v0': 3e-5,
    'vel.vcirc': 5e-4,
    'vel.rscale': 2e-5,
    'vel.x0': 3e-3,
    'vel.y0': 3e-4,
    'F087.flux': 2e-3,
    'F087.rscale': 3e-5,
    'F087.x0': 1e-6,
    'F087.y0': 1e-6,
    'Halpha.flux': 3e-4,
    'Halpha.rscale': 1e-5,
    'Halpha.x0': 2e-7,
    'Halpha.y0': 4e-5,
    'Halpha.dispersion': 2e-3,
}

# Error-bar references: the 1-sigma uncertainty implied by each slice's
# curvature with all other parameters held at truth, quoted at the
# matched-filter SNR=1000 noise convention. Measured 2026-07-08 on this
# frozen scene. A value outside the 20% band means the model's
# constraining power changed -- blurred, or artificially sharpened the
# way a coarse wavelength grid once faked a 6x tighter dispersion
# constraint -- and must be investigated, not casually re-frozen.
_JOINT_GRISM_SIGMA_REFS = {
    'cosi': 7.02e-4,
    'theta_int': 1.74e-3,
    'g1': 8.33e-4,
    'g2': 9.44e-4,
    'vel.v0': 0.695,
    'vel.vcirc': 3.32,
    'vel.rscale': 8.28e-3,
    'vel.x0': 3.76e-3,
    'vel.y0': 4.39e-3,
    'F087.flux': 0.100,
    'F087.rscale': 2.69e-4,
    'F087.x0': 3.81e-4,
    'F087.y0': 3.81e-4,
    'Halpha.flux': 0.100,
    'Halpha.rscale': 1.95e-4,
    'Halpha.x0': 2.82e-4,
    'Halpha.y0': 2.85e-4,
    'Halpha.dispersion': 4.80,
}


def test_recover_joint_phot_grism_base(test_config):
    """Joint velocity + broadband + emission-line grism likelihood slices
    on noise-free data.

    SourceModel with velocity (rotation curve drives Doppler), broadband
    F087 image, and Halpha emission line observed via grism. Truth
    distinguishes broadband and emission-line spatial profiles
    (``F087.rscale`` vs ``Halpha.rscale``; ``F087.x0`` vs ``Halpha.x0``)
    so the slices cover both pathways independently.

    Two deterministic gates per sampled parameter:

    - Accuracy: the 1-D slice peak must recover the truth within a tight
      absolute budget. The broadband data is rendered by GalSim, so its
      budgets bound our renderer against an independent reference; the
      grism data is self-rendered, so its budgets bound the forward
      model and estimator directly.
    - Information: the error bar implied by each slice's curvature must
      stay within 20% of its frozen reference, in either direction.

    The data carries no noise and the test has no random element: any
    failure is a real behavior change. Noise bookkeeping is covered by
    test_noise_calibration.py; recovery from noisy data belongs to the
    optimizer and sampler tiers. The grism renders through the analytic
    dispersal default; slice-pathway equivalence at production settings
    is pinned in test_analytic_dispersal.py.
    """
    import galsim as gs

    Z = 1.0
    snr = _JOINT_GRISM_SNR

    # Scales chosen so the source fits well inside the 32x32 image at
    # 0.11"/pix (extent ~1.76"); rscale > ~0.5" causes edge clipping that
    # GalSim and the k-space FFT handle differently, biasing the likelihood.
    F087_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 100.0,
        'rscale': 0.3,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    vel_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 0.4,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'z': Z,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 0.4,
        'vel.x0': 0.0,
        'vel.y0': 0.0,
        'F087.flux': 100.0,
        'F087.rscale': 0.3,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
        'Halpha.flux': 100.0,
        'Halpha.rscale': 0.2,
        'Halpha.h_over_r': 0.1,
        'Halpha.x0': 0.05,
        'Halpha.y0': 0.0,
        'Halpha.dispersion': 50.0,
    }

    psf = gs.Gaussian(fwhm=0.18)

    # Phot + grism share the same intensity grid so cube assembly + grism
    # dispersion stays at a manageable shape for the slice test.
    image_pars = ImagePars(shape=(32, 32), pixel_scale=0.11, indexing='ij')

    grism_pars = build_grism_pars_for_line(
        LINE_LAMBDAS['Halpha'],
        redshift=Z,
        image_pars=image_pars,
        dispersion=1.1,
    )

    # --- Broadband F087 data: GalSim-rendered, noise-free ---
    # variance follows the matched-filter convention at the nominal SNR;
    # it normalizes the likelihood (and the error-bar references) without
    # adding any noise to the data
    synth_int = SyntheticIntensity(
        F087_pars_flat,
        model_type='exponential',
        seed=test_config.seed,
        psf=psf,
    )
    synth_int.generate(
        image_pars,
        snr=snr,
        seed=test_config.seed,
        include_poisson=test_config.include_poisson_noise,
        sersic_backend='galsim',
    )
    data_int = np.asarray(synth_int.data_true)
    variance_int = synth_int.variance

    # --- SourceModel ---
    vel_model = OffsetVelocityModel()
    f087_int = InclinedExponentialModel()
    halpha_int = InclinedExponentialModel()
    source = SourceModel(
        velocity_model=vel_model,
        broadband_models={'F087': f087_int},
        emission_lines={'Halpha': EmissionLine(intensity=halpha_int)},
    )

    # --- Synthetic grism image (render via SourceModel, add Gaussian noise) ---
    # a likelihood-slice test requires data and fit to share one forward
    # pathway, so pin the same oversample on both (the builder default and
    # the priors-derived render config can differ)
    from kl_pipe.render import RenderConfig as _RC

    # the line window is pinned so data and fit share one forward pathway
    # exactly (the standalone render sizes it from the true parameter
    # values while the likelihood sizes it from prior extremes)
    rc_grism = _RC(
        oversample=5,
        dispersal_method='analytic',
        line_window_halfwidth=25,
    )
    grism_obs_clean = build_grism_obs(grism_pars, z=Z, psf=psf, render_config=rc_grism)
    clean_grism = np.asarray(source.render_grism(pars_dotted, grism_obs_clean))
    signal_power = float(np.sum(clean_grism**2))
    variance_grism = signal_power / snr**2

    # --- Obs construction (noise-free data) ---
    obs_int = build_image_obs(
        image_pars,
        psf=psf,
        data=jnp.asarray(data_int),
        variance=variance_int,
        int_model=f087_int,
        broadband_key='F087',
    )
    obs_grism = build_grism_obs(
        grism_pars,
        z=Z,
        psf=psf,
        data=jnp.asarray(clean_grism),
        variance=float(variance_grism),
        render_config=rc_grism,  # match the data pathway (see above)
    )

    # --- Data-vector diagnostics: one panel per channel ---
    test_name = "joint_phot_grism_base"
    # Broadband F087: clean signal via the noise-free obs (matches the
    # rendering path the likelihood uses internally).
    obs_int_noPSF = build_image_obs(
        image_pars, psf=psf, int_model=f087_int, broadband_key='F087'
    )
    clean_int = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_int),  # noise-free by design
        data_true=clean_int,
        model_eval=clean_int,  # model at truth == clean signal
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='F087_broadband',
        variance=np.asarray(variance_int),
        n_params=18,  # nominal sampled count for chi^2 dof; informational only
        enable_plots=test_config.enable_plots,
    )
    # Grism dispersed image
    plot_data_comparison_panels(
        data_noisy=np.asarray(clean_grism),  # noise-free by design
        data_true=clean_grism,
        model_eval=clean_grism,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='grism',
        variance=float(variance_grism),
        n_params=18,
        enable_plots=test_config.enable_plots,
    )

    extent = image_pars.shape[0] * image_pars.pixel_scale / 2
    # with noise-free data v0 has no noise floor to fight, so it is
    # sampled like everything else; its weak slitless constraint shows up
    # honestly in its error-bar reference instead
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'z': Z,  # fixed
        'vel.v0': Uniform(-100.0, 100.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(0.05, 2.0),
        'vel.x0': Uniform(-extent, extent),
        'vel.y0': Uniform(-extent, extent),
        'F087.flux': Uniform(10.0, 500.0),
        'F087.rscale': Uniform(0.05, 1.5),
        'F087.h_over_r': 0.1,  # fixed
        'F087.x0': Uniform(-extent, extent),
        'F087.y0': Uniform(-extent, extent),
        'Halpha.flux': Uniform(10.0, 500.0),
        'Halpha.rscale': Uniform(0.05, 1.5),
        'Halpha.h_over_r': 0.1,  # fixed
        'Halpha.x0': Uniform(-extent, extent),
        'Halpha.y0': Uniform(-extent, extent),
        'Halpha.dispersion': Uniform(10.0, 150.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(
        source,
        priors,
        image_obs={'F087': obs_int},
        grism_obs={'roll0': obs_grism},
    )
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=None,
    )

    recovery_stats = plot_likelihood_slices(
        slices,
        pars_dotted,
        test_name,
        test_config,
        snr,
        'joint',
        has_psf=True,
    )

    # gate 1: noise-free recovery within per-parameter accuracy budgets
    assert_noiseless_recovery(
        recovery_stats,
        _JOINT_GRISM_BUDGETS,
        'Joint vel+phot+grism (base)',
    )
    # gate 2: each slice's implied error bar matches its frozen reference
    assert_slice_curvature_references(
        slices,
        _JOINT_GRISM_SIGMA_REFS,
        'Joint vel+phot+grism (base)',
    )


# ==============================================================================
# Test: BulgeDisk Composite Likelihood Slice
# ==============================================================================


def test_recover_bulge_disk(test_config, snr=10000):
    """Likelihood slices for BulgeDiskModel composite recovery.

    Synthetic data is rendered through GalSim with PSF + pixel response on
    (``_TEST_PSF`` from test_composite_intensity). Noise convention matches
    other intensity slice tests via ``add_noise(include_poisson=False)``.
    """
    from test_composite_intensity import (
        _TRUE_PARS_SHARED,
        _IMAGE_PARS,
        _TEST_PSF,
        _generate_composite_synthetic,
    )

    X, Y = build_map_grid_from_image_pars(_IMAGE_PARS, unit='arcsec', centered=True)
    true_pars_flat = dict(_TRUE_PARS_SHARED)
    # Project flat composite keys into the F087 broadband namespace.
    # x0 / y0 strip their int_ prefix on resolution -> F087.x0/F087.y0.
    _SHARED = {'cosi', 'theta_int', 'g1', 'g2'}
    _PREFIX_STRIP = {'x0': 'x0', 'y0': 'y0'}
    pars_dotted = {}
    for k, v in true_pars_flat.items():
        if k in _SHARED:
            pars_dotted[k] = v
        else:
            bare = _PREFIX_STRIP.get(k, k)
            pars_dotted[f'F087.{bare}'] = v

    int_model = BulgeDiskModel(shared_centroids=True)
    source = SourceModel(broadband_models={'F087': int_model})

    data_true, data_noisy, variance = _generate_composite_synthetic(
        true_pars_flat, _IMAGE_PARS, snr, psf=_TEST_PSF
    )

    obs_int = build_image_obs(
        _IMAGE_PARS,
        psf=_TEST_PSF,
        data=data_true,
        variance=variance,
        int_model=int_model,
        broadband_key='F087',
    )

    # Render model through the same PSF + pixel-response path the likelihood
    # uses, so the diagnostic panels compare like-with-like (flux/pixel,
    # PSF-convolved).
    model_eval = np.array(
        source.render_broadband(pars_dotted, obs_int, band_key='F087')
    )

    test_name = 'bulge_disk'
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    # Priors: sampled params get Uniforms; pinned params (centroids = 0,
    # disk/bulge thickness aspect ratios at physical values) are fixed.
    priors_dict = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.x0': 0.0,  # fixed (resolves x0)
        'F087.y0': 0.0,  # fixed (resolves y0)
        'F087.total_flux': Uniform(0.1, 10.0),
        'F087.bulge_frac': Uniform(0.01, 0.99),
        'F087.disk_rscale': Uniform(0.5, 10.0),
        'F087.disk_h_over_r': 0.1,  # fixed
        'F087.bulge_hlr': Uniform(0.1, 3.0),
        'F087.bulge_h_over_hlr': 0.3,  # fixed
    }
    priors = PriorDict(priors_dict)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    slices = slice_all_parameters(
        log_like,
        sampled_names,
        theta_true_sampled,
        test_config,
        image_pars=_IMAGE_PARS,
    )

    recovery_stats = plot_likelihood_slices(
        slices,
        {n: pars_dotted[n] for n in sampled_names},
        test_name,
        test_config,
        snr,
        'intensity',
        has_psf=True,
        model_kind='composite',
    )

    assert_noiseless_gates(
        recovery_stats,
        slices,
        **_GATES['bulge_disk'],
        test_name='BulgeDisk likelihood slice',
    )


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
