"""
Parameter recovery tests using gradient-based optimization.

Similar to test_likelihood_slices.py, but uses scipy.optimize with
analytical gradients from JAX instead of brute-force likelihood slicing.

This tests:
1. That JAX gradients are computed correctly
2. That optimization can recover parameters efficiently
3. Comparison of optimizer performance vs likelihood slicing

The optimizer tests complement likelihood slicing by:
- Being much faster (gradients vs brute force)
- Testing in realistic inference scenarios
- Validating gradient implementations
"""

import pytest
import jax
import jax.numpy as jnp
import numpy as np
from scipy.optimize import minimize
from typing import Dict, Tuple

from kl_pipe.velocity import CenteredVelocityModel, OffsetVelocityModel
from kl_pipe.intensity import (
    InclinedExponentialModel,
    InclinedSpergelModel,
    BulgeDiskModel,
)
from kl_pipe.optimization import multi_start_minimize
from kl_pipe.source import SourceModel
from kl_pipe.lines import EmissionLine
from kl_pipe.parameters import ImagePars
from kl_pipe.priors import PriorDict, Uniform
from kl_pipe.sampling.task import InferenceTask
from kl_pipe.synthetic import SyntheticVelocity, SyntheticIntensity
from kl_pipe.observation import build_image_obs, build_velocity_obs
from kl_pipe.utils import build_map_grid_from_image_pars, get_test_dir
from kl_pipe.diagnostics.imaging import plot_data_comparison_panels

from test_utils import (
    TestConfig,
    assert_parameter_recovery,
    plot_parameter_comparison,
    check_degenerate_product_recovery,
    make_aperture_mask,
    suite_false_alarm_k,
    k_sigma_recovery_stats,
    optimizer_measure_mode,
    print_optimizer_sigma_entry,
    print_optimizer_bias_entry,
)


# ==============================================================================
# Frozen noise floors and the suite-wide bound multiplier
# ==============================================================================

# Marginal 1-sigma noise floors per test scene, measured from the
# likelihood curvature at truth on the model's own noise-free render,
# with each uniform prior box folded in as a Gaussian of equal variance.
# Frozen 2026-07-08 (commit c35e34e). Generated by this module's own
# measure mode -- regenerate with
#   KLPIPE_TEST_MEASURE=1 pytest tests/test_optimizer_recovery.py \
#       -k "10000 or not (1000 or 500)" -s
# (the -k selection runs each test only at its reference SNR, where the
# measurement is exact; measure mode prints ready-to-freeze entries,
# including the bulge_disk bias block).
# How to read the table: snr_ref is the HIGHEST SNR the test runs;
# floors rescale as 1/SNR, exact for data-dominated floors and
# conservative for prior-dominated ones. Each recovery check bounds
# |recovered - truth| by bias + _K * sigma. A prior-scale floor on a
# degenerate direction (e.g. cosi/g/vcirc/rscale in velocity-only
# scenes) is honest: the data cannot do better, and the vcirc*sin(i)
# product checks carry the physics there. 'biases' entries are 2x the
# measured noiseless-data recovery offset, rounded up to one
# significant figure -- used only where an independent rendering
# backend (GalSim) disagrees with the model by more than the noise
# floor. Update a value only deliberately, with the reason recorded
# here.
_OPT_SIGMAS = {
    'centered_velocity_base': {
        'snr_ref': 10000,
        'sigmas': {
            'cosi': 0.0658,
            'g1': 0.000345,
            'g2': 0.0549,
            'theta_int': 0.000282,
            'vel.rscale': 0.274,
            'vel.v0': 0.00479,
            'vel.vcirc': 12.3,
        },
    },
    'offset_velocity': {
        'snr_ref': 10000,
        'sigmas': {
            'cosi': 0.0659,
            'g1': 0.000295,
            'g2': 0.0548,
            'theta_int': 0.00113,
            'vel.rscale': 0.274,
            'vel.v0': 0.028,
            'vel.vcirc': 12.3,
            'vel.x0': 0.00192,
            'vel.y0': 0.00226,
        },
    },
    'centered_velocity_masked': {
        'snr_ref': 10000,
        'sigmas': {
            'cosi': 0.0658,
            'g1': 0.000448,
            'g2': 0.0549,
            'theta_int': 0.000343,
            'vel.rscale': 0.274,
            'vel.v0': 0.00541,
            'vel.vcirc': 12.3,
        },
    },
    'inclined_exponential': {
        'snr_ref': 10000,
        'sigmas': {
            'F087.flux': 0.000184,
            'F087.rscale': 0.00852,
            'F087.x0': 0.000382,
            'F087.y0': 0.000359,
            'cosi': 0.0041,
            'g1': 0.00604,
            'g2': 0.00287,
            'theta_int': 0.0178,
        },
    },
    'inclined_exponential_psf': {
        'snr_ref': 1000,
        'sigmas': {
            'F087.flux': 0.00183,
            'F087.rscale': 0.0917,
            'F087.x0': 0.00383,
            'F087.y0': 0.00382,
            'cosi': 0.044,
            'g1': 0.0463,
            'g2': 0.0309,
            'theta_int': 0.137,
        },
    },
    'inclined_exponential_masked': {
        'snr_ref': 1000,
        'sigmas': {
            'F087.flux': 0.00186,
            'F087.rscale': 0.0757,
            'F087.x0': 0.00382,
            'F087.y0': 0.00359,
            'cosi': 0.0365,
            'g1': 0.0415,
            'g2': 0.0255,
            'theta_int': 0.122,
        },
    },
    'joint_vel_phot_line_psf': {
        'snr_ref': 1000,
        'sigmas': {
            'F087.flux': 0.00195,
            'F087.rscale': 0.0989,
            'F087.x0': 0.00486,
            'F087.y0': 0.00484,
            'Halpha.rscale': 0.91,
            'Halpha.x0': 0.503,
            'Halpha.y0': 0.528,
            'cosi': 0.0309,
            'g1': 0.000884,
            'g2': 0.0251,
            'theta_int': 0.00108,
            'vel.rscale': 0.154,
            'vel.v0': 0.291,
            'vel.vcirc': 6.16,
            'vel.x0': 0.0193,
            'vel.y0': 0.0274,
        },
    },
    'joint_phot_grism_base': {
        'snr_ref': 10000,
        'sigmas': {
            'F087.flux': 0.0182,
            'F087.rscale': 0.00194,
            'F087.x0': 4.16e-05,
            'F087.y0': 4.16e-05,
            'Halpha.dispersion': 2.14,
            'Halpha.flux': 0.0181,
            'Halpha.rscale': 0.0013,
            'Halpha.x0': 0.000223,
            'Halpha.y0': 3.36e-05,
            'cosi': 0.00796,
            'g1': 0.00291,
            'g2': 0.00651,
            'theta_int': 0.0062,
            'vel.rscale': 0.00631,
            'vel.vcirc': 2.92,
            'vel.x0': 0.00254,
            'vel.y0': 0.00287,
        },
    },
    'joint_masked': {
        'snr_ref': 1000,
        'sigmas': {
            'F087.flux': 0.00185,
            'F087.rscale': 0.0654,
            'F087.x0': 0.00358,
            'F087.y0': 0.00358,
            'cosi': 0.0273,
            'g1': 0.000904,
            'g2': 0.0221,
            'theta_int': 0.00118,
            'vel.rscale': 0.131,
            'vel.v0': 0.333,
            'vel.vcirc': 5.2,
            'vel.x0': 0.0173,
            'vel.y0': 0.0237,
        },
    },
    'inclined_spergel': {
        'snr_ref': 10000,
        'sigmas': {
            'F087.flux': 0.000221,
            'F087.nu': 0.000912,
            'F087.rscale': 0.0128,
            'F087.x0': 0.000382,
            'F087.y0': 0.000359,
            'cosi': 0.00552,
            'g1': 0.00604,
            'g2': 0.00385,
            'theta_int': 0.0178,
        },
    },
    'inclined_spergel_psf': {
        'snr_ref': 1000,
        'sigmas': {
            'F087.flux': 0.0022,
            'F087.nu': 0.00893,
            'F087.rscale': 0.124,
            'F087.x0': 0.00383,
            'F087.y0': 0.00382,
            'cosi': 0.054,
            'g1': 0.0463,
            'g2': 0.0378,
            'theta_int': 0.137,
        },
    },
    'bulge_disk': {
        'snr_ref': 10000,
        'sigmas': {
            'F087.bulge_frac': 0.000269,
            'F087.bulge_hlr': 0.000824,
            'F087.disk_rscale': 0.00109,
            'F087.total_flux': 0.000389,
            'cosi': 0.000707,
            'g1': 0.000145,
            'g2': 0.000431,
            'theta_int': 0.000486,
        },
        # GalSim ground truth vs the n=4 emulator: measured noiseless
        # recovery offsets (frozen 2026-07-08, commit c35e34e; multi-
        # start, deterministic) exceed the SNR=10000 noise floor;
        # allowance = 2x measured, rounded up to one significant
        # figure. Regenerated by the same measure-mode command as the
        # sigma tables (this test prints its bias block).
        'biases': {
            'F087.bulge_frac': 7e-03,
            'F087.bulge_hlr': 3e-02,
            'F087.disk_rscale': 2e-02,
            'F087.total_flux': 4e-03,
            'cosi': 3e-02,
            'g1': 6e-06,
            'g2': 2e-02,
            'theta_int': 3e-05,
        },
    },
}

# Every parameter bounded above across all test instances (SNR variants
# included) shares one false-alarm budget of 1% for the whole module, so
# the multiplier is derived, not tuned (k = 4.04). Recount when adding or
# removing tests/parameters: sum of sigma-table sizes times SNR instances.
_N_BOUNDED_CHECKS = 184
_K = suite_false_alarm_k(_N_BOUNDED_CHECKS, budget=0.01)


# ==============================================================================
# Pytest Fixtures
# ==============================================================================


@pytest.fixture(scope="module")
def test_config():
    """Test configuration fixture."""
    out_dir = get_test_dir() / "out" / "optimizer_recovery"
    config = TestConfig(out_dir, include_poisson_noise=False)
    config.output_dir.mkdir(parents=True, exist_ok=True)
    return config


@pytest.fixture
def velocity_grids(test_config):
    """Pre-computed coordinate grids for velocity tests."""
    X, Y = build_map_grid_from_image_pars(
        test_config.image_pars_velocity, unit='arcsec', centered=True
    )
    return X, Y


@pytest.fixture
def intensity_grids(test_config):
    """Pre-computed coordinate grids for intensity tests."""
    X, Y = build_map_grid_from_image_pars(
        test_config.image_pars_intensity, unit='arcsec', centered=True
    )
    return X, Y


# ==============================================================================
# Helper Functions
# ==============================================================================


def generate_synthetic_velocity_data(
    model_class,
    true_pars: Dict[str, float],
    image_pars: ImagePars,
    snr: float,
    config: TestConfig,
) -> Tuple[jnp.ndarray, jnp.ndarray, float]:
    """Generate synthetic velocity data with noise."""
    model = model_class()
    vel_pars = {k: v for k, v in true_pars.items() if k in model.PARAMETER_NAMES}

    synth = SyntheticVelocity(vel_pars, model_type='arctan', seed=config.seed)
    data_noisy = synth.generate(image_pars, snr=snr, seed=config.seed)
    variance = synth.variance
    data_true = synth.data_true

    return data_true, data_noisy, variance


def generate_synthetic_intensity_data(
    model_class,
    true_pars: Dict[str, float],
    image_pars: ImagePars,
    snr: float,
    config: TestConfig,
    model_type: str = 'exponential',
) -> Tuple[jnp.ndarray, jnp.ndarray, float]:
    """Generate synthetic intensity data with noise."""
    model = model_class()
    int_pars = {k: v for k, v in true_pars.items() if k in model.PARAMETER_NAMES}

    synth = SyntheticIntensity(int_pars, model_type=model_type, seed=config.seed)
    data_noisy = synth.generate(
        image_pars,
        snr=snr,
        seed=config.seed,
        include_poisson=config.include_poisson_noise,
        sersic_backend=config.sersic_backend,
    )
    variance = synth.variance
    data_true = synth.data_true

    return data_true, data_noisy, variance


def optimize_with_gradients(
    log_like_fn: callable,
    theta_init: jnp.ndarray,
    bounds: list = None,
    method: str = 'L-BFGS-B',
) -> Tuple[jnp.ndarray, dict]:
    """
    Optimize using scipy with JAX gradients.

    Parameters
    ----------
    log_like_fn : callable
        JIT-compiled log-likelihood function.
    theta_init : jnp.ndarray
        Initial parameter guess.
    bounds : list, optional
        Parameter bounds as [(low, high), ...].
    method : str, optional
        Optimization method. Default is 'L-BFGS-B'.

    Returns
    -------
    theta_opt : jnp.ndarray
        Optimized parameters.
    result : dict
        Optimization result from scipy.
    """

    # Create gradient function using JAX
    grad_fn = jax.jit(jax.grad(log_like_fn))

    # Define objective (negative log-likelihood)
    def objective(theta):
        return -float(log_like_fn(jnp.array(theta)))

    def gradient(theta):
        return -np.array(grad_fn(jnp.array(theta)))

    # Run optimization
    # ftol is the relative change tolerance: (f_k - f_{k+1})/max{|f_k|,|f_{k+1}|,1} <= ftol
    result = minimize(
        objective,
        x0=np.array(theta_init),
        method=method,
        jac=gradient,
        bounds=bounds,
        options={'maxiter': 2000, 'ftol': 1e-8},
    )

    return jnp.array(result.x), result


# ==============================================================================
# Tests: Velocity Models
# ==============================================================================


@pytest.mark.parametrize("snr", [10000, 1000, 500])
def test_optimize_centered_velocity_base(snr, test_config, velocity_grids):
    """Test optimizer recovery for CenteredVelocityModel (no shear)."""

    X, Y = velocity_grids

    # Flat-key dict for SyntheticVelocity (REQUIRED_PARAMS['arctan']).
    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
    }
    # SourceModel dotted form.
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
    }

    vel_model = CenteredVelocityModel()
    source = SourceModel(velocity_model=vel_model)

    # Generate data
    data_true, data_noisy, variance = generate_synthetic_velocity_data(
        CenteredVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )

    # Diagnostic plot of truth via SourceModel render
    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    model_eval = np.asarray(source.render_velocity(pars_dotted, obs_vel_noPSF))
    test_name = f"opt_centered_vel_base_snr{snr}"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    # Build velocity obs WITH data + likelihood task. Measure mode fits
    # nothing: the likelihood is built on the model's own noise-free render
    # so its curvature at truth is exactly the information matrix.
    data_fit = model_eval if optimizer_measure_mode() else data_noisy
    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity, data=data_fit, variance=variance
    )
    # Every dotted param sampled with a wide Uniform so recovery exercises
    # the full parameter space.
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, velocity_obs=obs_vel)
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    if optimizer_measure_mode():
        # Velocity-only data with free shear constrains only vcirc*sin(i)
        # (the kinematic lensing degeneracy): without the prior term the
        # information matrix is numerically singular along the
        # cosi/g1/g2/vcirc/rscale subspace, so those floors come out at
        # prior-box scale (honest non-checks) and the vcirc*sini product
        # check carries the physics there.
        print_optimizer_sigma_entry(
            'centered_velocity_base',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=10000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    # 5% random perturbation on theta_true_sampled.
    rng = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.05 * theta_true_sampled * rng.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    # Optimize
    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)

    # Check convergence
    assert result.success, f"Optimization failed: {result.message}"

    # Evaluate model at optimized parameters for diagnostic plots
    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)
    model_eval_opt = np.asarray(source.render_velocity(pars_opt_dotted, obs_vel_noPSF))
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval_opt,
        test_name=f"{test_name}_optimized",
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance,
        n_params=len(pars_dotted),
        model_label='Optimized Model',
        enable_plots=test_config.enable_plots,
    )

    # Every sampled parameter bounded at _K times its marginal noise
    # floor; the degenerate cosi/g1/g2/vcirc/rscale subspace carries
    # honest prior-scale floors (see the measure-mode comment above) and
    # the vcirc*sini product check carries the physics there.
    entry = _OPT_SIGMAS['centered_velocity_base']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    # Check degenerate product vcirc*sini (helper accepts both 'vcirc' and 'vel.vcirc')
    product_passed, product_stats = check_degenerate_product_recovery(
        pars_dotted, pars_opt_dotted, snr=snr
    )

    plot_parameter_comparison(
        {n: pars_dotted[n] for n in recovery_stats},
        {n: pars_opt_dotted[n] for n in recovery_stats},
        recovery_stats,
        test_name,
        test_config,
        snr,
        product_stats=product_stats,
    )

    # Check if product passed
    if not product_passed:
        print(f"\n⚠️  Degenerate product vcirc*sini: {product_stats['formula']}")
        print(
            f"    True: {product_stats['true']:.2f}, Recovered: {product_stats['recovered']:.2f}"
        )
        print(
            f"    Rel error: {product_stats['rel_error']:.1%} (tolerance: {product_stats['tolerance']:.1%})"
        )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Centered velocity (base)',
    )
    assert (
        product_passed
    ), f"Degenerate product vcirc*sini not recovered: {product_stats['rel_error']:.1%} error"


@pytest.mark.parametrize("snr", [10000, 1000, 500])
def test_optimize_offset_velocity(snr, test_config, velocity_grids):
    """Test optimizer recovery for OffsetVelocityModel with shear."""

    X, Y = velocity_grids

    # Flat-key dict for SyntheticVelocity. x0/y0 are not in
    # REQUIRED_PARAMS['arctan'] but the synthetic generator ignores extras.
    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.02,
        'g2': -0.01,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
        'x0': 1.5,
        'y0': -1.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.02,
        'g2': -0.01,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
        'vel.x0': 1.5,
        'vel.y0': -1.0,
    }

    vel_model = OffsetVelocityModel()
    source = SourceModel(velocity_model=vel_model)

    # Generate data
    data_true, data_noisy, variance = generate_synthetic_velocity_data(
        OffsetVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )

    # Diagnostic plot of truth via SourceModel render
    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    model_eval = np.asarray(source.render_velocity(pars_dotted, obs_vel_noPSF))
    test_name = f"opt_offset_vel_snr{snr}"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    # Build velocity obs with data + likelihood task (model self-render in
    # measure mode so the curvature at truth is exactly the information
    # matrix)
    data_fit = model_eval if optimizer_measure_mode() else data_noisy
    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity, data=data_fit, variance=variance
    )
    extent = (
        test_config.image_pars_velocity.shape[0]
        * test_config.image_pars_velocity.pixel_scale
        / 2
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
        'vel.x0': Uniform(-extent, extent),
        'vel.y0': Uniform(-extent, extent),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, velocity_obs=obs_vel)
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    if optimizer_measure_mode():
        # Same kinematic-lensing degeneracy as the centered test: the
        # cosi/g1/g2/vcirc/rscale floors are prior-box scale and the
        # product check carries the physics there.
        print_optimizer_sigma_entry(
            'offset_velocity',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=10000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    # 5% random perturbation on theta_true_sampled.
    rng = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.05 * theta_true_sampled * rng.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    # Optimize
    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)
    assert result.success, f"Optimization failed: {result.message}"

    # Evaluate model at optimized parameters
    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)
    model_eval_opt = np.asarray(source.render_velocity(pars_opt_dotted, obs_vel_noPSF))
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval_opt,
        test_name=f"{test_name}_optimized",
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance,
        n_params=len(pars_dotted),
        model_label='Optimized Model',
        enable_plots=test_config.enable_plots,
    )

    # Every sampled parameter bounded at _K times its marginal noise
    # floor; the degenerate subspace carries honest prior-scale floors
    # and the product check carries the physics there.
    entry = _OPT_SIGMAS['offset_velocity']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    # Check degenerate product vcirc*sini
    product_passed, product_stats = check_degenerate_product_recovery(
        pars_dotted, pars_opt_dotted, snr=snr
    )

    plot_parameter_comparison(
        {n: pars_dotted[n] for n in recovery_stats},
        {n: pars_opt_dotted[n] for n in recovery_stats},
        recovery_stats,
        test_name,
        test_config,
        snr,
        product_stats=product_stats,
    )

    if not product_passed:
        print(f"\n⚠️  Degenerate product vcirc*sini: {product_stats['formula']}")
        print(
            f"    True: {product_stats['true']:.2f}, Recovered: {product_stats['recovered']:.2f}"
        )
        print(
            f"    Rel error: {product_stats['rel_error']:.1%} (tolerance: {product_stats['tolerance']:.1%})"
        )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Offset velocity with shear',
    )
    assert (
        product_passed
    ), f"Degenerate product vcirc*sini not recovered: {product_stats['rel_error']:.1%} error"


# ==============================================================================
# Tests: Intensity Models
# ==============================================================================


@pytest.mark.parametrize("snr", [10000, 1000, 500])
def test_optimize_inclined_exponential(snr, test_config, intensity_grids):
    """Test optimizer recovery for InclinedExponentialModel."""

    X, Y = intensity_grids

    # Flat-key dict for SyntheticIntensity.
    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    int_model = InclinedExponentialModel()
    source = SourceModel(broadband_models={'F087': int_model})

    # Generate data
    data_true, data_noisy, variance = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        true_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
    )

    # Diagnostic plot of truth via SourceModel render
    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_eval = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )
    test_name = f"opt_inclined_exp_snr{snr}"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    # Build image obs with data + likelihood task (model self-render in
    # measure mode so the curvature at truth is exactly the information
    # matrix)
    data_fit = model_eval if optimizer_measure_mode() else data_noisy
    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_fit,
        variance=variance,
        broadband_key='F087',
    )
    extent = (
        test_config.image_pars_intensity.shape[0]
        * test_config.image_pars_intensity.pixel_scale
        / 2
    )
    # Legacy bounds had (0.1, 0.1) for h_over_r — degenerate. Under
    # PriorDict, the SourceModel-native equivalent is to fix the parameter
    # as a numeric value (not sampled).
    priors_dict = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-extent, extent),
        'F087.y0': Uniform(-extent, extent),
    }
    priors = PriorDict(priors_dict)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    if optimizer_measure_mode():
        print_optimizer_sigma_entry(
            'inclined_exponential',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=10000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    # 5% random perturbation on theta_true_sampled.
    rng = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.05 * theta_true_sampled * rng.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    # Optimize
    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)
    assert result.success, f"Optimization failed: {result.message}"

    # Evaluate model at optimized parameters
    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)
    model_eval_opt = np.asarray(
        source.render_broadband(pars_opt_dotted, obs_int_noPSF, band_key='F087')
    )
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval_opt,
        test_name=f"{test_name}_optimized",
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        model_label='Optimized Model',
        enable_plots=test_config.enable_plots,
    )

    # Every sampled parameter bounded at _K times its marginal noise floor.
    entry = _OPT_SIGMAS['inclined_exponential']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    # Create parameter comparison plot (no vcirc*sini for intensity-only models).
    # Pass only sampled-name dicts so plot iterates over recovery_stats keys.
    plot_parameter_comparison(
        {n: pars_dotted[n] for n in sampled_names},
        {n: pars_opt_dotted[n] for n in sampled_names},
        recovery_stats,
        test_name,
        test_config,
        snr,
        product_stats=None,
    )

    # No vcirc*sini check for intensity-only models (no velocity field)
    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Inclined exponential intensity',
    )


# ==============================================================================
# Tests: PSF Recovery
# ==============================================================================


def test_optimize_inclined_exponential_with_psf(test_config, intensity_grids):
    """Test optimizer recovery for InclinedExponentialModel with PSF at SNR=1000."""
    import galsim as gs

    snr = 1000
    X, Y = intensity_grids

    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    psf = gs.Gaussian(fwhm=0.625)

    # generate PSF-convolved data via SyntheticIntensity (bare-model API)
    from kl_pipe.synthetic import SyntheticIntensity

    synth = SyntheticIntensity(
        true_pars_flat, model_type='exponential', seed=test_config.seed, psf=psf
    )
    data_noisy = synth.generate(
        test_config.image_pars_intensity,
        snr=snr,
        seed=test_config.seed,
        include_poisson=test_config.include_poisson_noise,
        sersic_backend='galsim',
    )
    variance = synth.variance

    # GalSim and model both produce flux/pixel; no conversion needed.

    # build SourceModel + obs with PSF (model self-render in measure mode
    # so the curvature at truth is exactly the information matrix)
    int_model = InclinedExponentialModel()
    source = SourceModel(broadband_models={'F087': int_model})

    if optimizer_measure_mode():
        obs_render = build_image_obs(
            test_config.image_pars_intensity,
            psf=psf,
            int_model=int_model,
            broadband_key='F087',
        )
        data_fit = source.render_broadband(pars_dotted, obs_render, band_key='F087')
    else:
        data_fit = data_noisy

    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        psf=psf,
        data=data_fit,
        variance=variance,
        int_model=int_model,
        broadband_key='F087',
    )

    extent = (
        test_config.image_pars_intensity.shape[0]
        * test_config.image_pars_intensity.pixel_scale
        / 2
    )
    priors_dict = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-extent, extent),
        'F087.y0': Uniform(-extent, extent),
    }
    priors = PriorDict(priors_dict)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    if optimizer_measure_mode():
        print_optimizer_sigma_entry(
            'inclined_exponential_psf',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=1000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    # 5% random perturbation on theta_true_sampled.
    rng = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.05 * theta_true_sampled * rng.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)
    assert result.success, f"Optimization failed: {result.message}"

    # check recovery: every sampled parameter bounded at _K times its
    # marginal noise floor
    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)
    entry = _OPT_SIGMAS['inclined_exponential_psf']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    test_name = f"opt_inclined_exp_psf_snr{snr}"
    plot_parameter_comparison(
        {n: pars_dotted[n] for n in sampled_names},
        {n: pars_opt_dotted[n] for n in sampled_names},
        recovery_stats,
        test_name,
        test_config,
        snr,
    )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Inclined exponential (PSF)',
    )


# ==============================================================================
# Test: Joint Velocity + Broadband + Emission Line with PSF
# ==============================================================================


def test_optimize_joint_vel_phot_line_with_psf(
    test_config, velocity_grids, intensity_grids
):
    """Joint vel + broadband + emission-line optimizer recovery at SNR=1000.

    Validates the line-driven velocity-PSF flux weighting path. The
    SourceModel has a velocity model, a broadband (F087) component
    fitting the intensity image, and an Halpha emission line whose
    spatial profile drives ``VelocityObs.flux_weight_key='Halpha'``.

    Truth distinguishes broadband and emission-line spatial profiles
    (``F087.rscale=4.0`` vs ``Halpha.rscale=2.0``; ``F087.x0=0.0`` vs
    ``Halpha.x0=0.2``) so the test exercises both pathways independently.
    """
    import galsim as gs

    snr = 1000

    # Flat-key dicts for the bare-model synthetic generators.
    F087_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 4.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    Halpha_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 2.0,
        'h_over_r': 0.1,
        'x0': 0.2,
        'y0': 0.0,
    }
    vel_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
        'x0': 0.0,
        'y0': 0.0,
    }
    # SourceModel dotted dict (single source of truth for likelihood path).
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
        'vel.x0': 0.0,
        'vel.y0': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 4.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
        'Halpha.flux': 1.0,
        'Halpha.rscale': 2.0,
        'Halpha.h_over_r': 0.1,
        'Halpha.x0': 0.2,
        'Halpha.y0': 0.0,
    }

    psf = gs.Gaussian(fwhm=0.625)

    # --- Synthetic data generation ---
    from kl_pipe.synthetic import (
        SyntheticIntensity,
        SyntheticVelocity,
        generate_sersic_intensity_2d,
    )

    # F087 broadband image: PSF-convolved, on intensity grid.
    synth_int = SyntheticIntensity(
        F087_pars_flat,
        model_type='exponential',
        seed=test_config.seed,
        psf=psf,
    )
    data_int_noisy = synth_int.generate(
        test_config.image_pars_intensity,
        snr=snr,
        seed=test_config.seed,
        include_poisson=test_config.include_poisson_noise,
        sersic_backend='galsim',
    )
    variance_int = synth_int.variance

    # Halpha spatial profile rendered on the velocity grid -- drives the
    # velocity PSF flux weighting. Use Halpha truth (distinct from F087).
    halpha_flux_image = generate_sersic_intensity_2d(
        test_config.image_pars_velocity,
        backend='scipy',
        n_sersic=1.0,
        **{k: v for k, v in Halpha_pars_flat.items() if k != 'n_sersic'},
    )

    # Velocity map: PSF + flux-weighted by Halpha intensity.
    synth_vel = SyntheticVelocity(
        vel_pars_flat,
        model_type='arctan',
        seed=test_config.seed + 1,
        psf=psf,
        intensity_for_psf=halpha_flux_image,
    )
    data_vel_noisy = synth_vel.generate(
        test_config.image_pars_velocity,
        snr=snr,
        seed=test_config.seed + 1,
    )
    variance_vel = synth_vel.variance

    # --- SourceModel + obs construction ---
    vel_model = OffsetVelocityModel()
    f087_int = InclinedExponentialModel()
    halpha_int = InclinedExponentialModel()
    source = SourceModel(
        velocity_model=vel_model,
        broadband_models={'F087': f087_int},
        emission_lines={'Halpha': EmissionLine(intensity=halpha_int)},
    )

    # model self-render in measure mode so the likelihood curvature at
    # truth is exactly the information matrix
    measure = optimizer_measure_mode()
    if measure:
        obs_vel_render = build_velocity_obs(
            test_config.image_pars_velocity, psf=psf, flux_weight_key='Halpha'
        )
        obs_int_render = build_image_obs(
            test_config.image_pars_intensity,
            psf=psf,
            int_model=f087_int,
            broadband_key='F087',
        )
        data_vel_fit = source.render_velocity(pars_dotted, obs_vel_render)
        data_int_fit = source.render_broadband(
            pars_dotted, obs_int_render, band_key='F087'
        )
    else:
        data_vel_fit = data_vel_noisy
        data_int_fit = data_int_noisy
    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity,
        psf=psf,
        data=data_vel_fit,
        variance=variance_vel,
        flux_weight_key='Halpha',
    )
    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        psf=psf,
        data=data_int_fit,
        variance=variance_int,
        int_model=f087_int,
        broadband_key='F087',
    )

    extent_vel = (
        test_config.image_pars_velocity.shape[0]
        * test_config.image_pars_velocity.pixel_scale
        / 2
    )
    extent_int = (
        test_config.image_pars_intensity.shape[0]
        * test_config.image_pars_intensity.pixel_scale
        / 2
    )

    # 19 sampled params (4 shared + 5 vel + 5 F087 + 5 Halpha).
    priors_dict = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
        'vel.x0': Uniform(-extent_vel, extent_vel),
        'vel.y0': Uniform(-extent_vel, extent_vel),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-extent_int, extent_int),
        'F087.y0': Uniform(-extent_int, extent_int),
        'Halpha.flux': Uniform(0.1, 10.0),
        'Halpha.rscale': Uniform(0.5, 10.0),
        'Halpha.h_over_r': 0.1,  # fixed (not sampled)
        'Halpha.x0': Uniform(-extent_vel, extent_vel),
        'Halpha.y0': Uniform(-extent_vel, extent_vel),
    }
    priors = PriorDict(priors_dict)
    task = InferenceTask.from_obs(
        source, priors, velocity_obs=obs_vel, image_obs={'F087': obs_int}
    )
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    # Halpha enters this data only through the velocity channel's flux
    # weighting, which is normalized (weighted velocity = conv(I*v) /
    # conv(I)), so the likelihood is exactly flat along Halpha.flux and
    # the parameter is unidentifiable here. Pin that fact: if a config
    # change ever makes it constrained, this fails and Halpha.flux must
    # rejoin the recovery check below.
    ha_flux_idx = sampled_names.index('Halpha.flux')
    ll_true = float(log_like(theta_true_sampled))
    ll_scaled = float(log_like(theta_true_sampled.at[ha_flux_idx].mul(2.0)))
    assert abs(ll_scaled - ll_true) < 1e-8 * max(abs(ll_true), 1.0), (
        "Halpha.flux moved the likelihood -- it is now identifiable and "
        "must be restored to the recovery pass/fail check"
    )

    if measure:
        # Halpha.flux is exactly flat (pinned above): dropped so its
        # vacuous prior-scale floor does not enter the check count.
        print_optimizer_sigma_entry(
            'joint_vel_phot_line_psf',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=1000,
            drop=('Halpha.flux',),
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    # 5% perturbation initial guess.
    rng = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.05 * theta_true_sampled * rng.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)
    assert result.success, f"Optimization failed: {result.message}"

    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)

    # Every sampled parameter bounded at _K times its marginal noise floor.
    # Halpha.flux is absent from the sigma table: it enters this data only
    # through the velocity channel's normalized flux weighting, so the
    # amplitude cancels exactly (pinned flat above) and it ends wherever
    # the perturbed init left it.
    entry = _OPT_SIGMAS['joint_vel_phot_line_psf']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    product_passed, product_stats = check_degenerate_product_recovery(
        pars_dotted, pars_opt_dotted, snr=snr
    )

    test_name = f"opt_joint_vel_phot_line_psf_snr{snr}"
    plot_parameter_comparison(
        {n: pars_dotted[n] for n in recovery_stats},
        {n: pars_opt_dotted[n] for n in recovery_stats},
        recovery_stats,
        test_name,
        test_config,
        snr,
        product_stats=product_stats,
    )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Joint vel+phot+line (PSF)',
    )
    assert (
        product_passed
    ), f"Degenerate product vcirc*sini not recovered: {product_stats['rel_error']:.1%} error"


# ==============================================================================
# Test: Joint Velocity + Broadband + Grism (line) Optimizer Recovery
# ==============================================================================


def test_optimize_joint_phot_grism_base(test_config):
    """Joint vel + broadband + emission-line grism optimizer recovery, SNR=10000.

    Optimizer-level counterpart to ``test_recover_joint_phot_grism_base`` in
    test_likelihood_slices.py. Same SourceModel + truth + synthetic data
    pathway; uses scipy.optimize with JAX gradients to recover parameters.

    SNR=10000 (not 1000): the vcirc Fisher precision in grism+phot data is
    ~17% at SNR=1000 (full Hessian; line FWHM in dispersed image is set by
    PSF+dispersion ~430 km/s, not by detector pixel width), so the
    vcirc*sin(i) product check cannot reliably pass at SNR=1000 with any
    reasonable tolerance. At SNR=10000 the Fisher floor drops to ~1% and
    the default product tolerance (10% for SNR not in the explicit dict)
    passes comfortably with the default test_config.seed=42 (measured
    vcirc*sini error: +2.1%). Note: a small fraction of noise realizations
    (~10% of seeds in a 10-seed scan) trap single-start L-BFGS-B in local
    minima up to ~30% off; if a future change to test_config.seed surfaces
    this, switch to multi-start optimization (pattern in
    test_optimize_bulge_disk via kl_pipe.optimization.multi_start_minimize).

    vel.v0 is fixed at truth here. The renderer DOES include v0 in the
    Doppler shift (pinned by ``test_v0_shifts_cube`` in
    test_source_render.py), but its conditional Fisher under grism+phot
    data is weak (~1.2% at SNR=10000); the test is about cosi/vcirc/rscale
    recovery, not v0.
    """
    import galsim as gs

    snr = 10000
    Z = 1.0

    F087_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 100.0,
        'rscale': 0.3,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'z': Z,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 0.4,
        'vel.x0': 0.0,
        'vel.y0': 0.0,
        'F087.flux': 100.0,
        'F087.rscale': 0.3,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
        'Halpha.flux': 100.0,
        'Halpha.rscale': 0.2,
        'Halpha.h_over_r': 0.1,
        'Halpha.x0': 0.05,
        'Halpha.y0': 0.0,
        'Halpha.dispersion': 50.0,
    }

    psf = gs.Gaussian(fwhm=0.18)
    image_pars = ImagePars(shape=(32, 32), pixel_scale=0.11, indexing='ij')

    from kl_pipe.dispersion import build_grism_pars_for_line
    from kl_pipe.lines import LINE_LAMBDAS
    from kl_pipe.observation import build_grism_obs

    grism_pars = build_grism_pars_for_line(
        LINE_LAMBDAS['Halpha'],
        redshift=Z,
        image_pars=image_pars,
        dispersion=1.1,
    )

    # --- Synthetic F087 broadband image ---
    synth_int = SyntheticIntensity(
        F087_pars_flat,
        model_type='exponential',
        seed=test_config.seed,
        psf=psf,
    )
    data_int_noisy = synth_int.generate(
        image_pars,
        snr=snr,
        seed=test_config.seed,
        include_poisson=test_config.include_poisson_noise,
        sersic_backend='galsim',
    )
    variance_int = synth_int.variance

    # --- SourceModel ---
    vel_model = OffsetVelocityModel()
    f087_int = InclinedExponentialModel()
    halpha_int = InclinedExponentialModel()
    source = SourceModel(
        velocity_model=vel_model,
        broadband_models={'F087': f087_int},
        emission_lines={'Halpha': EmissionLine(intensity=halpha_int)},
    )

    # --- Synthetic grism image (render via SourceModel, add Gaussian noise) ---
    grism_obs_clean = build_grism_obs(grism_pars, z=Z, psf=psf)
    clean_grism = np.asarray(source.render_grism(pars_dotted, grism_obs_clean))
    signal_power = float(np.sum(clean_grism**2))
    variance_grism = signal_power / snr**2
    rng = np.random.default_rng(test_config.seed + 2)
    noise_grism = rng.normal(0.0, np.sqrt(variance_grism), size=clean_grism.shape)
    data_grism_noisy = clean_grism + noise_grism

    # model self-render in measure mode so the likelihood curvature at
    # truth is exactly the information matrix (clean_grism already is the
    # model's own render)
    measure = optimizer_measure_mode()
    if measure:
        obs_int_render = build_image_obs(
            image_pars, psf=psf, int_model=f087_int, broadband_key='F087'
        )
        data_int_fit = source.render_broadband(
            pars_dotted, obs_int_render, band_key='F087'
        )
    else:
        data_int_fit = data_int_noisy
    obs_int = build_image_obs(
        image_pars,
        psf=psf,
        data=jnp.asarray(data_int_fit),
        variance=variance_int,
        int_model=f087_int,
        broadband_key='F087',
    )
    obs_grism = build_grism_obs(
        grism_pars,
        z=Z,
        psf=psf,
        data=jnp.asarray(clean_grism if measure else data_grism_noisy),
        variance=float(variance_grism),
    )

    extent = image_pars.shape[0] * image_pars.pixel_scale / 2
    priors_dict = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'z': Z,  # fixed
        'vel.v0': pars_dotted['vel.v0'],  # fixed (unconstrained by phot+grism)
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(0.05, 2.0),
        'vel.x0': Uniform(-extent, extent),
        'vel.y0': Uniform(-extent, extent),
        'F087.flux': Uniform(10.0, 500.0),
        'F087.rscale': Uniform(0.05, 1.5),
        'F087.h_over_r': 0.1,  # fixed
        'F087.x0': Uniform(-extent, extent),
        'F087.y0': Uniform(-extent, extent),
        'Halpha.flux': Uniform(10.0, 500.0),
        'Halpha.rscale': Uniform(0.05, 1.5),
        'Halpha.h_over_r': 0.1,  # fixed
        'Halpha.x0': Uniform(-extent, extent),
        'Halpha.y0': Uniform(-extent, extent),
        'Halpha.dispersion': Uniform(10.0, 150.0),
    }
    priors = PriorDict(priors_dict)
    task = InferenceTask.from_obs(
        source,
        priors,
        image_obs={'F087': obs_int},
        grism_obs={'roll0': obs_grism},
    )
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    if measure:
        print_optimizer_sigma_entry(
            'joint_phot_grism_base',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=10000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    # B.4c uses 1% init perturbation, not the 5% used elsewhere. Empirically
    # (seed scan with default_rng, SNR=10000), 5% perturbation pushes
    # single-start L-BFGS-B into a non-truth local minimum on a substantial
    # fraction of seeds for this geometry (joint vel+phot+grism without
    # velocity-MAP data has shallower off-ridge Fisher than other tests).
    # 1% stays inside the truth basin; all params recover within their
    # tolerances. Multi-start would also work but costs ~3x wallclock for
    # this single test. If a future change to test_config.seed surfaces a
    # different bad noise realization, switch to multi-start (pattern in
    # test_optimize_bulge_disk via kl_pipe.optimization.multi_start_minimize).
    rng_init = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.01 * theta_true_sampled * rng_init.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)
    assert result.success, f"Optimization failed: {result.message}"

    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)

    # Every sampled parameter bounded at _K times its marginal noise floor.
    entry = _OPT_SIGMAS['joint_phot_grism_base']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    product_passed, product_stats = check_degenerate_product_recovery(
        pars_dotted, pars_opt_dotted, snr=snr
    )

    test_name = f"opt_joint_phot_grism_base_snr{snr}"
    plot_parameter_comparison(
        {n: pars_dotted[n] for n in recovery_stats},
        {n: pars_opt_dotted[n] for n in recovery_stats},
        recovery_stats,
        test_name,
        test_config,
        snr,
        product_stats=product_stats,
    )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Joint phot+grism (base)',
    )
    assert (
        product_passed
    ), f"Degenerate product vcirc*sini not recovered: {product_stats['rel_error']:.1%} error"


# ==============================================================================
# Tests: Masked Optimizer Recovery
# ==============================================================================


def test_optimize_centered_velocity_masked(test_config, velocity_grids):
    """Optimizer recovery with masked velocity data at SNR=10000."""
    X, Y = velocity_grids
    snr = 10000

    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
    }

    vel_model = CenteredVelocityModel()
    source = SourceModel(velocity_model=vel_model)

    data_true, data_noisy, variance = generate_synthetic_velocity_data(
        CenteredVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )

    mask = make_aperture_mask(data_noisy.shape)

    # model self-render in measure mode (masked information matrix)
    if optimizer_measure_mode():
        obs_render = build_velocity_obs(test_config.image_pars_velocity)
        data_fit = source.render_velocity(pars_dotted, obs_render)
    else:
        data_fit = data_noisy
    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity,
        data=data_fit,
        variance=variance,
        mask=jnp.array(mask),
    )
    sampled_priors = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
    }
    priors = PriorDict(sampled_priors)
    task = InferenceTask.from_obs(source, priors, velocity_obs=obs_vel)
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    if optimizer_measure_mode():
        # Same kinematic-lensing degeneracy as the unmasked test.
        print_optimizer_sigma_entry(
            'centered_velocity_masked',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=10000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    rng = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.05 * theta_true_sampled * rng.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)
    assert result.success, f"Optimization failed: {result.message}"

    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)

    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    model_eval_opt = np.asarray(source.render_velocity(pars_opt_dotted, obs_vel_noPSF))
    test_name = f"opt_centered_vel_masked_snr{snr}"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval_opt,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance,
        n_params=len(pars_dotted),
        model_label='Optimized Model',
        enable_plots=test_config.enable_plots,
        mask=mask,
    )

    # Every sampled parameter bounded at _K times its marginal noise
    # floor; the degenerate subspace carries honest prior-scale floors
    # and the product check carries the physics there.
    entry = _OPT_SIGMAS['centered_velocity_masked']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    product_passed, product_stats = check_degenerate_product_recovery(
        pars_dotted, pars_opt_dotted, snr=snr
    )

    plot_parameter_comparison(
        {n: pars_dotted[n] for n in recovery_stats},
        {n: pars_opt_dotted[n] for n in recovery_stats},
        recovery_stats,
        test_name,
        test_config,
        snr,
        product_stats=product_stats,
    )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Centered velocity (masked)',
    )
    assert product_passed, (
        f"Degenerate product vcirc*sini not recovered: "
        f"{product_stats['rel_error']:.1%} error"
    )


def test_optimize_inclined_exponential_masked(test_config, intensity_grids):
    """Optimizer recovery with masked intensity data at SNR=1000."""
    X, Y = intensity_grids
    snr = 1000

    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    int_model = InclinedExponentialModel()
    source = SourceModel(broadband_models={'F087': int_model})

    data_true, data_noisy, variance = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        true_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
    )

    mask = make_aperture_mask(data_noisy.shape)

    # model self-render in measure mode (masked information matrix)
    if optimizer_measure_mode():
        obs_render = build_image_obs(
            test_config.image_pars_intensity, broadband_key='F087'
        )
        data_fit = source.render_broadband(pars_dotted, obs_render, band_key='F087')
    else:
        data_fit = data_noisy
    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_fit,
        variance=variance,
        mask=jnp.array(mask),
        broadband_key='F087',
    )

    extent = (
        test_config.image_pars_intensity.shape[0]
        * test_config.image_pars_intensity.pixel_scale
        / 2
    )
    priors_dict = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-extent, extent),
        'F087.y0': Uniform(-extent, extent),
    }
    priors = PriorDict(priors_dict)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    if optimizer_measure_mode():
        print_optimizer_sigma_entry(
            'inclined_exponential_masked',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=1000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    rng = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.05 * theta_true_sampled * rng.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)
    assert result.success, f"Optimization failed: {result.message}"

    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)

    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_eval_opt = np.asarray(
        source.render_broadband(pars_opt_dotted, obs_int_noPSF, band_key='F087')
    )
    test_name = f"opt_inclined_exp_masked_snr{snr}"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval_opt,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        model_label='Optimized Model',
        enable_plots=test_config.enable_plots,
        mask=mask,
    )

    # Every sampled parameter bounded at _K times its marginal noise floor.
    entry = _OPT_SIGMAS['inclined_exponential_masked']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    plot_parameter_comparison(
        {n: pars_dotted[n] for n in sampled_names},
        {n: pars_opt_dotted[n] for n in sampled_names},
        recovery_stats,
        test_name,
        test_config,
        snr,
        product_stats=None,
    )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Inclined exponential (masked)',
    )


def test_optimize_joint_masked(test_config, velocity_grids, intensity_grids):
    """Optimizer recovery for joint vel+phot model with both masks at SNR=1000."""
    snr = 1000
    X_vel, Y_vel = velocity_grids
    X_int, Y_int = intensity_grids

    true_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'v0': 10.0,
        'vcirc': 200.0,
        'rscale': 5.0,
        'x0': 0.0,
        'y0': 0.0,
    }
    int_pars_flat = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.6,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'vel.v0': 10.0,
        'vel.vcirc': 200.0,
        'vel.rscale': 5.0,
        'vel.x0': 0.0,
        'vel.y0': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    vel_model = OffsetVelocityModel()
    int_model = InclinedExponentialModel()
    source = SourceModel(
        velocity_model=vel_model,
        broadband_models={'F087': int_model},
    )

    data_vel_true, data_vel_noisy, variance_vel = generate_synthetic_velocity_data(
        OffsetVelocityModel,
        true_pars_flat,
        test_config.image_pars_velocity,
        snr,
        test_config,
    )
    data_int_true, data_int_noisy, variance_int = generate_synthetic_intensity_data(
        InclinedExponentialModel,
        int_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
    )

    mask_vel = make_aperture_mask(data_vel_noisy.shape)
    mask_int = make_aperture_mask(data_int_noisy.shape)

    # model self-render in measure mode (masked information matrix)
    measure = optimizer_measure_mode()
    if measure:
        obs_vel_render = build_velocity_obs(test_config.image_pars_velocity)
        obs_int_render = build_image_obs(
            test_config.image_pars_intensity, broadband_key='F087'
        )
        data_vel_fit = source.render_velocity(pars_dotted, obs_vel_render)
        data_int_fit = source.render_broadband(
            pars_dotted, obs_int_render, band_key='F087'
        )
    else:
        data_vel_fit = data_vel_noisy
        data_int_fit = data_int_noisy
    obs_vel = build_velocity_obs(
        test_config.image_pars_velocity,
        data=data_vel_fit,
        variance=variance_vel,
        mask=jnp.array(mask_vel),
    )
    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_int_fit,
        variance=variance_int,
        mask=jnp.array(mask_int),
        broadband_key='F087',
    )

    extent_vel = (
        test_config.image_pars_velocity.shape[0]
        * test_config.image_pars_velocity.pixel_scale
        / 2
    )
    extent_int = (
        test_config.image_pars_intensity.shape[0]
        * test_config.image_pars_intensity.pixel_scale
        / 2
    )
    priors_dict = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'vel.v0': Uniform(0.0, 50.0),
        'vel.vcirc': Uniform(100.0, 350.0),
        'vel.rscale': Uniform(1.0, 20.0),
        'vel.x0': Uniform(-extent_vel, extent_vel),
        'vel.y0': Uniform(-extent_vel, extent_vel),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        'F087.x0': Uniform(-extent_int, extent_int),
        'F087.y0': Uniform(-extent_int, extent_int),
    }
    priors = PriorDict(priors_dict)
    task = InferenceTask.from_obs(
        source, priors, velocity_obs=obs_vel, image_obs={'F087': obs_int}
    )
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    if measure:
        print_optimizer_sigma_entry(
            'joint_masked',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=1000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    rng = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.05 * theta_true_sampled * rng.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)
    assert result.success, f"Optimization failed: {result.message}"

    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)

    obs_vel_noPSF = build_velocity_obs(test_config.image_pars_velocity)
    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_vel_opt = np.asarray(source.render_velocity(pars_opt_dotted, obs_vel_noPSF))
    model_int_opt = np.asarray(
        source.render_broadband(pars_opt_dotted, obs_int_noPSF, band_key='F087')
    )

    test_name = f"opt_joint_masked_snr{snr}"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_vel_noisy),
        data_true=np.asarray(data_vel_true),
        model_eval=model_vel_opt,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='velocity',
        variance=variance_vel,
        n_params=5,
        model_label='Optimized Model',
        enable_plots=test_config.enable_plots,
        mask=mask_vel,
    )
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_int_noisy),
        data_true=np.asarray(data_int_true),
        model_eval=model_int_opt,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance_int,
        n_params=5,
        model_label='Optimized Model',
        enable_plots=test_config.enable_plots,
        mask=mask_int,
    )

    # Every sampled parameter bounded at _K times its marginal noise floor.
    entry = _OPT_SIGMAS['joint_masked']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    product_passed, product_stats = check_degenerate_product_recovery(
        pars_dotted, pars_opt_dotted, snr=snr
    )
    plot_parameter_comparison(
        {n: pars_dotted[n] for n in sampled_names},
        {n: pars_opt_dotted[n] for n in sampled_names},
        recovery_stats,
        test_name,
        test_config,
        snr,
        product_stats=product_stats,
    )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Joint model (masked)',
    )


# ==============================================================================
# Spergel Intensity Model Optimizer Recovery
# ==============================================================================


@pytest.mark.parametrize("snr", [10000, 1000])
def test_optimize_inclined_spergel(snr, test_config, intensity_grids):
    """Test optimizer recovery for InclinedSpergelModel."""

    X, Y = intensity_grids

    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'nu': 0.5,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.03,
        'g2': -0.02,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.nu': 0.5,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    int_model = InclinedSpergelModel()
    source = SourceModel(broadband_models={'F087': int_model})

    data_true, data_noisy, variance = generate_synthetic_intensity_data(
        InclinedSpergelModel,
        true_pars_flat,
        test_config.image_pars_intensity,
        snr,
        test_config,
        model_type='spergel',
    )

    obs_int_noPSF = build_image_obs(
        test_config.image_pars_intensity, broadband_key='F087'
    )
    model_eval = np.asarray(
        source.render_broadband(pars_dotted, obs_int_noPSF, band_key='F087')
    )
    test_name = f"opt_inclined_spergel_snr{snr}"
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval,
        test_name=test_name,
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        enable_plots=test_config.enable_plots,
    )

    # model self-render in measure mode so the curvature at truth is
    # exactly the information matrix
    data_fit = model_eval if optimizer_measure_mode() else data_noisy
    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        data=data_fit,
        variance=variance,
        broadband_key='F087',
    )

    extent = (
        test_config.image_pars_intensity.shape[0]
        * test_config.image_pars_intensity.pixel_scale
        / 2
    )
    priors_dict = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        # nu lower bound >= -0.5 to stay clear of the inclined-cusp regime that
        # SourceModel's check_priors_safe rejects when cosi is also free.
        'F087.nu': Uniform(-0.5, 4.0),
        'F087.x0': Uniform(-extent, extent),
        'F087.y0': Uniform(-extent, extent),
    }
    priors = PriorDict(priors_dict)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    if optimizer_measure_mode():
        print_optimizer_sigma_entry(
            'inclined_spergel',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=10000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    rng = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.05 * theta_true_sampled * rng.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)
    assert result.success, f"Optimization failed: {result.message}"

    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)
    model_eval_opt = np.asarray(
        source.render_broadband(pars_opt_dotted, obs_int_noPSF, band_key='F087')
    )
    plot_data_comparison_panels(
        data_noisy=np.asarray(data_noisy),
        data_true=np.asarray(data_true),
        model_eval=model_eval_opt,
        test_name=f"{test_name}_optimized",
        output_dir=test_config.output_dir / test_name,
        data_type='intensity',
        variance=variance,
        n_params=len(pars_dotted),
        model_label='Optimized Model',
        enable_plots=test_config.enable_plots,
    )

    # Every sampled parameter bounded at _K times its marginal noise floor.
    entry = _OPT_SIGMAS['inclined_spergel']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    plot_parameter_comparison(
        {n: pars_dotted[n] for n in sampled_names},
        {n: pars_opt_dotted[n] for n in sampled_names},
        recovery_stats,
        test_name,
        test_config,
        snr,
        product_stats=None,
    )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Inclined Spergel',
    )


def test_optimize_inclined_spergel_with_psf(test_config, intensity_grids):
    """Test optimizer recovery for InclinedSpergelModel with PSF (SNR=1000 only)."""
    import galsim as gs

    snr = 1000
    X, Y = intensity_grids

    # Flat-key dict for SyntheticIntensity.
    true_pars_flat = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'flux': 1.0,
        'rscale': 3.0,
        'h_over_r': 0.1,
        'nu': 0.5,
        'x0': 0.0,
        'y0': 0.0,
    }
    pars_dotted = {
        'cosi': 0.7,
        'theta_int': 0.785,
        'g1': 0.0,
        'g2': 0.0,
        'F087.flux': 1.0,
        'F087.rscale': 3.0,
        'F087.h_over_r': 0.1,
        'F087.nu': 0.5,
        'F087.x0': 0.0,
        'F087.y0': 0.0,
    }

    psf = gs.Gaussian(fwhm=0.625)

    # generate PSF-convolved data with oversample=5 to match model's pixel response
    from kl_pipe.synthetic import SyntheticIntensity

    synth = SyntheticIntensity(
        true_pars_flat, model_type='spergel', seed=test_config.seed, psf=psf
    )
    data_noisy = synth.generate(
        test_config.image_pars_intensity,
        snr=snr,
        seed=test_config.seed,
        include_poisson=test_config.include_poisson_noise,
        oversample=5,
    )
    variance = synth.variance
    data_true = synth.data_true

    int_model = InclinedSpergelModel()
    source = SourceModel(broadband_models={'F087': int_model})

    # model self-render in measure mode
    if optimizer_measure_mode():
        obs_render = build_image_obs(
            test_config.image_pars_intensity,
            psf=psf,
            int_model=int_model,
            broadband_key='F087',
        )
        data_fit = source.render_broadband(pars_dotted, obs_render, band_key='F087')
    else:
        data_fit = data_noisy
    obs_int = build_image_obs(
        test_config.image_pars_intensity,
        psf=psf,
        data=data_fit,
        variance=variance,
        int_model=int_model,
        broadband_key='F087',
    )

    extent = (
        test_config.image_pars_intensity.shape[0]
        * test_config.image_pars_intensity.pixel_scale
        / 2
    )
    priors_dict = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.flux': Uniform(0.1, 10.0),
        'F087.rscale': Uniform(0.5, 10.0),
        'F087.h_over_r': 0.1,  # fixed (not sampled)
        # nu lower bound >= -0.5 to stay clear of the inclined-cusp regime.
        'F087.nu': Uniform(-0.5, 4.0),
        'F087.x0': Uniform(-extent, extent),
        'F087.y0': Uniform(-extent, extent),
    }
    priors = PriorDict(priors_dict)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])

    if optimizer_measure_mode():
        print_optimizer_sigma_entry(
            'inclined_spergel_psf',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=1000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        return

    rng = np.random.default_rng(test_config.seed)
    theta_init = theta_true_sampled + 0.05 * theta_true_sampled * rng.normal(
        size=len(theta_true_sampled)
    )

    bounds = [priors._priors[n].bounds for n in sampled_names]

    theta_opt, result = optimize_with_gradients(log_like, theta_init, bounds)
    assert result.success, f"Optimization failed: {result.message}"

    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)

    # Every sampled parameter bounded at _K times its marginal noise floor.
    entry = _OPT_SIGMAS['inclined_spergel_psf']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
    )

    test_name = f"opt_inclined_spergel_psf_snr{snr}"
    plot_parameter_comparison(
        {n: pars_dotted[n] for n in sampled_names},
        {n: pars_opt_dotted[n] for n in sampled_names},
        recovery_stats,
        test_name,
        test_config,
        snr,
        product_stats=None,
    )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'Optimizer: Inclined Spergel (PSF)',
    )


# ==============================================================================
# Test: BulgeDisk Composite Optimizer Recovery
# ==============================================================================


@pytest.mark.parametrize('snr', [10000, 1000])
def test_optimize_bulge_disk(snr, test_config):
    """Multi-start L-BFGS-B optimizer recovery for BulgeDiskModel.

    Multi-start (literature standard for B+D fits: Sheth+ 2010 / Erwin 2015 /
    Robotham+ 2017) rather than single-start because the bulge+disk likelihood
    has a documented ``bulge_frac=0`` boundary attractor — single-start
    L-BFGS-B from a 5% perturbation reliably converges to the wrong basin
    (catastrophically at low SNR).

    Synthetic data is rendered with PSF + pixel response on; noise via
    ``add_noise(include_poisson=False)`` matching every other intensity test.
    """
    from test_composite_intensity import (
        _TRUE_PARS_SHARED,
        _IMAGE_PARS,
        _TEST_PSF,
        _generate_composite_synthetic,
    )

    true_pars_flat = dict(_TRUE_PARS_SHARED)
    # Project flat composite keys into the F087 broadband namespace.
    # Shared geometry (cosi, theta_int, g1, g2) stays unprefixed.
    # x0 / y0 strip their int_ prefix on resolution -> F087.x0/F087.y0.
    _SHARED = {'cosi', 'theta_int', 'g1', 'g2'}
    _PREFIX_STRIP = {'x0': 'x0', 'y0': 'y0'}
    pars_dotted = {}
    for k, v in true_pars_flat.items():
        if k in _SHARED:
            pars_dotted[k] = v
        else:
            bare = _PREFIX_STRIP.get(k, k)
            pars_dotted[f'F087.{bare}'] = v

    int_model = BulgeDiskModel(shared_centroids=True)
    source = SourceModel(broadband_models={'F087': int_model})

    data_true, data_noisy, variance = _generate_composite_synthetic(
        true_pars_flat, _IMAGE_PARS, snr, psf=_TEST_PSF
    )

    # model self-render in measure mode
    if optimizer_measure_mode():
        obs_render = build_image_obs(
            _IMAGE_PARS, psf=_TEST_PSF, int_model=int_model, broadband_key='F087'
        )
        data_fit = source.render_broadband(pars_dotted, obs_render, band_key='F087')
    else:
        data_fit = data_noisy
    obs_int = build_image_obs(
        _IMAGE_PARS,
        psf=_TEST_PSF,
        data=data_fit,
        variance=variance,
        int_model=int_model,
        broadband_key='F087',
    )

    # Priors: sampled params get Uniforms; pinned params (centroids fixed
    # at 0, disk/bulge thickness aspect ratios at their physical values) are
    # numeric fixed values.
    priors_dict = {
        'cosi': Uniform(0.1, 0.99),
        'theta_int': Uniform(0.0, np.pi),
        'g1': Uniform(-0.1, 0.1),
        'g2': Uniform(-0.1, 0.1),
        'F087.x0': 0.0,  # fixed (resolves x0 in BulgeDiskModel)
        'F087.y0': 0.0,  # fixed (resolves y0)
        'F087.total_flux': Uniform(0.1, 10.0),
        'F087.bulge_frac': Uniform(0.01, 0.99),
        'F087.disk_rscale': Uniform(0.5, 10.0),
        'F087.disk_h_over_r': 0.1,  # fixed
        'F087.bulge_hlr': Uniform(0.1, 3.0),
        'F087.bulge_h_over_hlr': 0.3,  # fixed
    }
    priors = PriorDict(priors_dict)
    task = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_int})
    log_like = task.likelihood_fn

    sampled_names = list(priors.sampled_names)
    theta_true_sampled = jnp.array([pars_dotted[n] for n in sampled_names])
    bounds = [priors._priors[n].bounds for n in sampled_names]

    def run_multi_start(fit_log_like):
        neg_ll_and_grad = jax.jit(jax.value_and_grad(lambda t: -fit_log_like(t)))

        def objective(x):
            val, grad = neg_ll_and_grad(jnp.array(x))
            return float(val), np.array(grad, dtype=np.float64)

        result = multi_start_minimize(
            objective,
            np.array(theta_true_sampled),
            bounds=bounds,
            n_starts=10,
            perturbation=0.2,
            method='L-BFGS-B',
            seed=42,
            fixed_indices=None,
            jac=True,
            options={'maxiter': 2000, 'ftol': 1e-8},
        )
        assert result.success, f'Optimization failed: {result.message}'
        return jnp.array(result.x)

    if optimizer_measure_mode():
        print_optimizer_sigma_entry(
            'bulge_disk',
            log_like,
            theta_true_sampled,
            sampled_names,
            snr=snr,
            snr_ref=10000,
            prior_bounds={n: priors._priors[n].bounds for n in sampled_names},
        )
        # bias measurement: fit the noise-free GalSim render directly; the
        # recovered offset from truth is the deterministic rendering
        # difference between GalSim and the emulator
        obs_bias = build_image_obs(
            _IMAGE_PARS,
            psf=_TEST_PSF,
            data=data_true,
            variance=variance,
            int_model=int_model,
            broadband_key='F087',
        )
        task_bias = InferenceTask.from_obs(source, priors, image_obs={'F087': obs_bias})
        theta_bias = run_multi_start(task_bias.likelihood_fn)
        print_optimizer_bias_entry(
            'bulge_disk', theta_true_sampled, theta_bias, sampled_names
        )
        return

    theta_opt = run_multi_start(log_like)
    pars_opt_dotted = dict(pars_dotted)
    for n, v in zip(sampled_names, theta_opt):
        pars_opt_dotted[n] = float(v)

    # Every sampled parameter bounded at bias + _K times its marginal
    # noise floor (centroids + thickness aspect ratios are pinned in
    # priors and so absent from the sigma table). The bias allowance
    # covers the measured GalSim-vs-emulator rendering offset, which
    # exceeds the noise floor at SNR=10000.
    entry = _OPT_SIGMAS['bulge_disk']
    recovery_stats = k_sigma_recovery_stats(
        pars_dotted,
        pars_opt_dotted,
        sampled_names,
        entry['sigmas'],
        _K,
        snr=snr,
        snr_ref=entry['snr_ref'],
        biases=entry['biases'],
    )

    assert_parameter_recovery(
        recovery_stats,
        snr,
        'BulgeDisk optimizer',
    )


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
