"""Render the parameter provenance table from the registry.

Writes two artifacts:
  1. parameter_table.tex (paper mode, \\citet citations) into the paper repo,
     ready to \\input from main.tex.
  2. parameter_table.pdf (standalone longtable, citations hyperlinked via the
     DOI/arXiv fields parsed from the paper's refs.bib), easy to share.

The registry imports every numeric from the module that uses it, so this
script is the only sanctioned way to refresh the table; never edit the
generated .tex by hand.

Usage:
    python scripts/render_parameter_table.py --run-dir <expanded run dir>

The run dir supplies the production spec + observation config (any expanded
catalog-mode run works, e.g. runs/cosmos25_ab_bb32gr32).
"""

import argparse
import re
import shutil
import subprocess
import tempfile
from datetime import date
from pathlib import Path

from kl_pipe.ensemble.expander import load_run
from kl_pipe.ensemble.prior_provenance import (
    catalog_registry,
    registry_to_latex,
    standalone_document,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PAPER_REPO = REPO_ROOT / 'docs' / 'papers' / 'kl-roman-pipeline'


def cite_urls_from_bib(bib_path: Path) -> dict:
    """Bibkey -> URL from refs.bib, preferring doi over arXiv eprint."""
    text = bib_path.read_text()
    urls: dict = {}
    for m in re.finditer(r'@\w+\{(?P<key>[^,]+),(?P<body>.*?)\n\}', text, re.S):
        key = m.group('key').strip()
        body = m.group('body')
        doi = re.search(r'doi\s*=\s*\{([^}]+)\}', body)
        eprint = re.search(r'eprint\s*=\s*\{([^}]+)\}', body)
        if doi:
            urls[key] = f'https://doi.org/{doi.group(1).strip()}'
        elif eprint:
            urls[key] = f'https://arxiv.org/abs/{eprint.group(1).strip()}'
    return urls


def paper_header() -> str:
    sha = subprocess.run(
        ['git', 'rev-parse', '--short', 'HEAD'],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    return (
        '% Parameter provenance table, generated by '
        'scripts/render_parameter_table.py\n'
        '% from kl_pipe.ensemble.prior_provenance (mode=paper), '
        f'kl_roman_pipe @ {sha}, {date.today().isoformat()}.\n'
        '% Regenerate from the pipeline rather than editing values by hand; '
        'the registry\n'
        '% imports every numeric from the module that uses it and a coverage '
        'test pins\n'
        '% the row set.\n'
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        '--run-dir',
        required=True,
        help='expanded catalog-mode run dir supplying spec + config',
    )
    ap.add_argument(
        '--paper-repo',
        default=str(DEFAULT_PAPER_REPO),
        help='paper repo checkout (default: docs/papers/kl-roman-pipeline)',
    )
    ap.add_argument('--skip-pdf', action='store_true', help='write the .tex files only')
    args = ap.parse_args()

    paper_repo = Path(args.paper_repo)
    if not paper_repo.is_dir():
        raise FileNotFoundError(f'paper repo not found: {paper_repo}')

    spec, config, _ = load_run(args.run_dir)
    registry = catalog_registry(spec, config)
    print(f'{len(registry)} parameters in registry')

    paper_tex = paper_repo / 'parameter_table.tex'
    paper_tex.write_text(paper_header() + registry_to_latex(registry, mode='paper'))
    print(f'wrote {paper_tex}')

    if args.skip_pdf:
        return

    urls = cite_urls_from_bib(paper_repo / 'refs.bib')
    doc = standalone_document(registry, cite_urls=urls)
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / 'parameter_table.tex'
        src.write_text(doc)
        subprocess.run(
            ['latexmk', '-pdf', '-interaction=nonstopmode', src.name],
            cwd=tmp,
            capture_output=True,
            text=True,
            check=True,
        )
        pdf_out = paper_repo / 'parameter_table.pdf'
        shutil.copy(Path(tmp) / 'parameter_table.pdf', pdf_out)
    print(f'wrote {pdf_out}')


if __name__ == '__main__':
    main()
